// main.js
// Language toggle: instant DOM swap, localStorage persistence,
// navigator.language default. No page reload, no scroll jump.

(function () {
  const IEL_URL_EN = "https://utulsa.edu/academics/interdisciplinary-programs/international-engineering-science-language/";
  const IEL_URL_ES = "https://utulsa-edu.translate.goog/academics/interdisciplinary-programs/international-engineering-science-language/?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=en";
  const STORAGE_KEY = "lang";

  // Document links — resume / CV / transcript buttons opt in with
  // data-doc-link="resume" | "cv" | "transcript". Paths come from the generated
  // manifest js/docs-data.js (const DOCS — see scripts/build-docs-manifest.js,
  // regenerated by the pre-commit hook), loaded before this file on every page.
  // No network requests: the old date-probing + localStorage cache is gone.
  //
  // Resolution per element: active language → the other language → leave the
  // element's existing href. A doc type with no file in ANY language hides its
  // buttons (hidden attribute) rather than linking to nothing. If the manifest
  // failed to load, nothing is touched.
  const DOC_CACHE_PREFIX = "docUrl_"; // legacy probe cache — removed once on load

  (function removeLegacyDocCache() {
    try {
      Object.keys(localStorage)
        .filter(function (k) { return k.indexOf(DOC_CACHE_PREFIX) === 0; })
        .forEach(function (k) { localStorage.removeItem(k); });
    } catch (e) { /* storage unavailable — nothing to clean */ }
  }());

  function encodeDocPath(p) {
    return p.split("/").map(encodeURIComponent).join("/");
  }

  // The manifest slot for a type: { en, es } for bilingual types, { any } for
  // the transcript. Returns the path for `lang`, else the other language, else null.
  function docPathFor(docType, lang) {
    const slot = DOCS[docType];
    if (!slot) return null;
    if (slot.any !== undefined) return slot.any || null;
    return slot[lang] || slot[lang === "en" ? "es" : "en"] || null;
  }

  function updateResumeLinks(lang) {
    if (typeof DOCS === "undefined") return; // manifest missing — leave hrefs alone
    document.querySelectorAll("[data-doc-link]").forEach(function (el) {
      const docType = el.getAttribute("data-doc-link");
      const p = docPathFor(docType, lang);
      if (!p) {
        el.hidden = true; // no file for this type at all
        return;
      }
      el.hidden = false;
      el.setAttribute("href", encodeDocPath(p));
    });
  }

  function detectDefaultLang() {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === "en" || stored === "es") return stored;

    const nav = (navigator.language || "en").toLowerCase();
    // Spanish-locale or Portuguese (lusophone) → ES default. Else EN.
    if (nav.startsWith("es") || nav.startsWith("pt")) return "es";
    return "en";
  }

  const BOTS_URL_EN = "https://automatetheboringstuff.com/";
  const BOTS_URL_ES = "https://automatetheboringstuff-com.translate.goog/?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=en";

  // Ordered list of (phrase, url-per-lang) pairs to auto-link inside hero text.
  const HERO_CHIPS = [
    { phrase: /\bIEL\b/, urls: { en: IEL_URL_EN, es: IEL_URL_ES } },
    { phrase: /automating the boring stuff/, urls: { en: BOTS_URL_EN, es: BOTS_URL_ES } },
    { phrase: /automatizar lo aburrido/, urls: { en: BOTS_URL_EN, es: BOTS_URL_ES } }
  ];

  function withHeroChips(text, lang) {
    return HERO_CHIPS.reduce(function (acc, chip) {
      const url = chip.urls[lang];
      return acc.replace(chip.phrase, function (match) {
        return '<a class="iel-chip" href="' + url + '" target="_blank" rel="noopener">' + match + '</a>';
      });
    }, text);
  }

  function renderHeroParagraphs() {
    document.querySelectorAll("[data-hero-lang]").forEach(function (el) {
      const lang = el.getAttribute("data-hero-lang");
      const dict = translations[lang];
      if (dict && dict.heroDesc) {
        el.innerHTML = withHeroChips(dict.heroDesc, lang);
      }
    });
  }

  function updateHeroActiveState(lang) {
    document.querySelectorAll("[data-hero-lang]").forEach(function (el) {
      const isActive = el.getAttribute("data-hero-lang") === lang;
      el.classList.toggle("is-active", isActive);
      el.classList.toggle("is-inactive", !isActive);
    });
  }

  // data-i18n keys whose translation string contains markup (e.g. an <a> link)
  // and must be injected as HTML rather than escaped as plain text.
  const HTML_I18N_KEYS = ["aiPara1"];

  function applyTranslations(lang) {
    const dict = translations[lang];
    if (!dict) return;

    document.querySelectorAll("[data-i18n]").forEach(function (el) {
      const key = el.getAttribute("data-i18n");
      if (dict[key] === undefined) return;
      if (HTML_I18N_KEYS.indexOf(key) !== -1) {
        el.innerHTML = dict[key];
      } else {
        el.textContent = dict[key];
      }
    });

    document.querySelectorAll("[data-i18n-alt]").forEach(function (el) {
      const key = el.getAttribute("data-i18n-alt");
      if (dict[key] === undefined) return;
      el.setAttribute("alt", dict[key]);
    });

    updateResumeLinks(lang);

    document.querySelectorAll(".lang-toggle .lang-btn").forEach(function (span) {
      span.classList.toggle("is-active", span.getAttribute("data-lang") === lang);
    });

    document.documentElement.setAttribute("lang", lang);
    updateHeroActiveState(lang);

    // Lets page-specific scripts (e.g. js/about.js) refresh content that is
    // rendered from JS data arrays rather than driven directly by data-i18n.
    document.dispatchEvent(new CustomEvent("langchange", { detail: { lang: lang } }));
  }

  function setLang(lang) {
    localStorage.setItem(STORAGE_KEY, lang);
    applyTranslations(lang);
  }

  const langToggleBtn = document.querySelector("[data-lang-toggle]");
  if (langToggleBtn) {
    langToggleBtn.addEventListener("click", function () {
      const current = document.documentElement.getAttribute("lang") === "es" ? "es" : "en";
      setLang(current === "en" ? "es" : "en");
    });
  }

  // Mobile hamburger — open/close nav dropdown
  (function () {
    var hamburger = document.getElementById("hamburger");
    var dropdown = document.getElementById("nav-dropdown");
    if (!hamburger || !dropdown) return;

    function openMenu() {
      dropdown.classList.add("is-open");
      hamburger.classList.add("is-open");
      hamburger.setAttribute("aria-expanded", "true");
      dropdown.setAttribute("aria-hidden", "false");
    }

    function closeMenu() {
      dropdown.classList.remove("is-open");
      hamburger.classList.remove("is-open");
      hamburger.setAttribute("aria-expanded", "false");
      dropdown.setAttribute("aria-hidden", "true");
    }

    hamburger.addEventListener("click", function (e) {
      e.stopPropagation();
      if (dropdown.classList.contains("is-open")) {
        closeMenu();
      } else {
        openMenu();
      }
    });

    // Close when a nav link is tapped
    dropdown.querySelectorAll("a").forEach(function (link) {
      link.addEventListener("click", closeMenu);
    });

    // Close when clicking outside the dropdown or hamburger
    document.addEventListener("click", function (e) {
      if (!hamburger.contains(e.target) && !dropdown.contains(e.target)) {
        closeMenu();
      }
    });

    // Close on Escape key
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") closeMenu();
    });
  }());

  renderHeroParagraphs();
  applyTranslations(detectDefaultLang());
})();
