"""Where the transcript pieces live (repo-relative, posix)."""

SCRIPT_DIR = "scripts/transcript"
PARSER = "parse_transcript.py"
BUILDER = "make_transcript.py"
FILES = {
    "titles": "course-titles.json",
    "profile": "profile.json",
    "adjustments": "adjustments.json",
    "data": "transcript-data.json",  # generated by the parser; shown, never edited here
}
EDITABLE = ("titles", "profile", "adjustments")
RAW_DIR = "references/transcripts"  # TU's PDFs (student ID inside) — gitignored
OUTPUT_DIR = "scripts/transcript/output"  # .docx from the builder — gitignored
BUILT_DIR = "staging/transcript-out"  # PDFs before publishing — gitignored
LABEL = "Transcript"
PUB_TYPE = "transcript"


def rel(name: str) -> str:
    return f"{SCRIPT_DIR}/{FILES[name]}"
