// strings.js — Uneven scatter (Reading Your Fits, Module 3).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js. `es` is filled in during the Spanish pass.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Uneven Scatter · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 3",
    h1: "Uneven Scatter",
    lead: "Many sensors are rated as a percentage of the reading, so big readings carry big errors. The fitted line survives that. The error bars don't.",
    introHtml: "When the scatter grows (or shrinks) along the fit, the residual plot fans out. Statisticians call this <i>heteroskedasticity</i>: uneven scatter. Here the sensor's error is a fixed 0.5 units plus a percentage of the reading, like many datasheets state it. All data is simulated from y = 1 + 2x, so the true slope is <b>2.00</b>.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "Ordinary least-squares fit and its band",
    keyFix: "Weighted fit and its band",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",

    pctLabel: "Sensor error, % of reading",
    pctHelp: "Plus a fixed 0.5 units. Datasheets often say \"±0.5 + 10% of reading\".",
    pctFmt: "{p}%",
    btnNewSample: "Draw a new sample",
    axX: "x",
    axY: "measured y",
    axFittedY: "fitted y",
    axResidual: "residual",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "The fan",
    t1Intro: "Turn up the percentage part of the sensor's error and watch the residual plot.",
    roSlope: "Fitted slope",
    roTrue: "True slope",
    roLow: "Residual spread, low third",
    roHigh: "Residual spread, high third",
    roRatio: "High ÷ low",
    ratioFmt: "{r}×",
    t1DataAria: "Data with the fitted and true lines",
    t1DataCapHtml: "<b>The data and the fit.</b> 40 readings.",
    t1ResidAria: "Residuals against fitted value",
    t1ResidCapHtml: "<b>Residual plot.</b> Spread measured as the SD of the residuals in the lowest and highest third of fitted values.",
    t1NoteEvenHtml: "<b>The scatter is about even at this setting.</b> In this sample the high end spreads {r}× as much as the low end; with only 13 points per third, chance alone can give ratios up to about 1.6. Turn the percentage up.",
    t1NoteFanHtml: "<b>A fan: the sensor is about {tr}× noisier at x = 9 than at x = 2,</b> and in this sample the high end of the residuals spreads {r}× as much as the low end (chance moves that number around; draw a few samples). The fitted slope ({b}) is still about right; uneven scatter doesn't bias the line. What goes wrong is every statement about how uncertain it is. Trial 2 shows that.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "The error bars lie",
    t2Intro: "The experiment is repeated 400 times. Each time, the ordinary fit draws a 95% band where the next reading should land, and a 95% range for the slope. How often are they right?",
    t2PatLabel: "Where the sensor is worst",
    patHigh: "High readings",
    patEnds: "Both ends",
    t2PatHelp: "Both ends: the error is 0.5 in the middle of the range and grows toward each end, reaching the high-reading case's size at the edges.",
    t2BandAria: "One sample with the ordinary prediction band and 200 new readings at x = 2 and x = 9",
    t2BandCapHtml: "<b>One fit's 95% band, and 200 new readings at x = 2 and x = 9.</b> Red dots fall outside the band.",
    t2BarsAria: "How often each 95% promise held over 400 repeats",
    t2BarsCapHtml: "<b>How often each 95% promise held,</b> over 400 repeats. Dashed line: 95%.",
    barLow: "x=2 band",
    barHigh: "x=9 band",
    barSlopeDef: "slope",
    barSlopeRob: "robust slope",
    axCaught: "caught (%)",
    roPiLow: "Band catches new reading at x = 2",
    roPiHigh: "Band catches new reading at x = 9",
    roCiDef: "Slope range catches 2.00 (default)",
    roCiRob: "Slope range catches 2.00 (robust)",
    pctOf: "{p}%",
    t2NoteEvenHtml: "<b>With even scatter every promise holds:</b> about 95% everywhere.",
    t2NoteFanHtml: "<b>The band is one width everywhere, but the scatter isn't.</b> At x = 2 it catches {lo}% of new readings and at x = 9 {hi}%, against a promised 95%. Too wide wastes precision where readings are quiet; too narrow promises more than noisy readings can deliver. ",
    t2NoteSlopeBadHtml: "<b>The slope's default range is too narrow as well:</b> it catches 2.00 only {def}% of the time. Robust (HC3) standard errors fix that without changing the line: {rob}%.",
    t2NoteSlopeEndsMildHtml: "The slope's default range is only slightly narrow at this setting ({def}%); turn the error up and it gets worse. Robust (HC3) standard errors stay honest: {rob}%.",
    t2NoteSlopeOkHtml: "The slope's default range holds up here ({def}%): with the noise piled at one end, its errors happen to cancel. Switch to Both ends and they won't. Robust (HC3) standard errors are right either way: {rob}%.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "Weight each point by how much you trust it",
    t3Intro: "If you know each reading's uncertainty (from the datasheet or from repeat readings), a weighted fit gives each point a weight of 1/σ², so precise readings count more. Compare it with the ordinary fit.",
    t3MethodLabel: "Fit",
    mOls: "Ordinary",
    mWls: "Weighted (1/σ²)",
    t3DataAria: "Data with the chosen fit and its 95% prediction band",
    t3DataCapHtml: "<b>The chosen fit and its 95% band</b> for the next reading.",
    t3SpreadAria: "Spread of fitted slopes over 400 repeats for both methods",
    t3SpreadCapHtml: "<b>Fitted slopes from 400 repeats,</b> both methods. The narrower pile is the more precise method.",
    roOlsSd: "Slope scatter (SD), ordinary",
    roWlsSd: "Slope scatter (SD), weighted",
    roPiLow3: "Band catches new reading at x = 2",
    roPiHigh3: "Band catches new reading at x = 9",
    lblOls: "ordinary",
    lblWls: "weighted",
    axFittedSlope: "fitted slope",
    axRepeats: "repeats",
    t3NoteOlsHtml: "<b>The ordinary fit treats every point as equally trustworthy.</b> Its band has one width, so it misses at the noisy end. Switch to Weighted.",
    t3NoteWlsHtml: "<b>The weighted band widens where the sensor is worse,</b> and now catches about 95% at both ends ({lo}% and {hi}%). Its slope also scatters less from run to run (SD {w} against {o} for the ordinary fit), because it leans on the precise readings. The catch: you need a fair estimate of each reading's σ.",
    t3NoteEvenHtml: "<b>With even scatter, the two fits agree.</b> Weighting only helps when the points aren't equally trustworthy.",
    logSummary: "What about taking the log?",
    logBodyHtml: "If the error is <i>purely</i> a percentage of the reading and the physics is multiplicative (y = a·x<sup>b</sup>, or exponential growth or decay), fitting log y makes the scatter even. It also changes what the coefficients mean, and a fixed error part (the 0.5 here) comes back as uneven scatter at small readings. When you know σ for each point, weighting is the more direct fix.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>A fan in the residual plot means uneven scatter.</b> Check the shape first (Module 2): a curve can look like a fan.",
    take2Html: "<b>The line is still about right. The error bars aren't:</b> too wide where readings are quiet, too narrow where they're noisy.",
    take3Html: "<b>If you know each reading's σ, weight by 1/σ².</b> Your datasheet usually tells you. Otherwise, use robust (HC3) standard errors for honest slope ranges.",
    take4Html: "<b>Pooling two instruments or sessions</b> with different precision creates the same problem. Weight them, or fit them separately.",
    checkTitle: "How to do it",
    check1Title: "Excel",
    check1Body: "No weighted fit built in. Multiply each row's x, y and a column of 1s by √w, then use LINEST with no constant.",
    check2Title: "MATLAB",
    check2Body: "fitlm(x, y, 'Weights', 1./sigma.^2). Robust errors: hac(x, y, 'type', 'HC', 'weights', 'HC3') in the Econometrics Toolbox. (fitlm's 'RobustOpts' is something else: it downweights outliers.)",
    check3Title: "Python",
    check3Body: "statsmodels: sm.WLS(y, X, weights=1/sigma**2). Robust: .fit(cov_type='HC3'). scipy: curve_fit(..., sigma=sigma, absolute_sigma=True).",
    footNote: "Simulated data. True model y = 1 + 2x; sensor error SD = 0.5 + p% of the true reading.",
    footRead: "Further reading: Long and Ervin (2000), \"Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model\"; MacKinnon and White (1985), \"Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties\"; White (1980), \"A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity\"."
  },
  es: {},
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "HC3" }, href: "long-ervin-2000.pdf" },
    { phrase: { en: "\"Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model\"" }, href: "long-ervin-2000.pdf" },
    { phrase: { en: "\"Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties\"" }, href: "mackinnon-white-1985.pdf" },
    { phrase: { en: "\"A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity\"" }, href: "white-1980.pdf" }
  ]
};
