// strings.js — Uneven scatter (Reading Your Fits, Module 3).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Uneven Scatter · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 3",
    h1: "Uneven Scatter",
    lead: "Many sensors are rated as a percentage of the reading, so big readings carry big errors. The fitted line survives that. The error bars don't.",
    introHtml: "When the scatter grows (or shrinks) along the fit, the residual plot fans out. Statisticians call this <i>heteroskedasticity</i>: uneven scatter. Here the sensor's error is a fixed 0.5 units plus a percentage of the reading, like many datasheets state it. All data is simulated from y = 1 + 2x, so the true slope is <b>2.00</b>.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "Ordinary least-squares fit and its band",
    keyFix: "Weighted fit and its band",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    takePlay: "Play with the code",
    takeColab: "Open in Colab",

    pctLabel: "Sensor error, % of reading",
    pctHelp: "Plus a fixed 0.5 units. Datasheets often say \"±0.5 + 10% of reading\".",
    pctFmt: "{p}%",
    btnNewSample: "Draw a new sample",
    axX: "x",
    axY: "measured y",
    axFittedY: "fitted y",
    axResidual: "residual",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "The fan",
    t1Intro: "Turn up the percentage part of the sensor's error and watch the residual plot.",
    roSlope: "Fitted slope",
    roTrue: "True slope",
    roLow: "Residual spread, low third",
    roHigh: "Residual spread, high third",
    roRatio: "High ÷ low",
    ratioFmt: "{r}×",
    t1DataAria: "Data with the fitted and true lines",
    t1DataCapHtml: "<b>The data and the fit.</b> 40 readings.",
    t1ResidAria: "Residuals against fitted value",
    t1ResidCapHtml: "<b>Residual plot.</b> Spread measured as the SD of the residuals in the lowest and highest third of fitted values.",
    t1NoteEvenHtml: "<b>The scatter is about even at this setting.</b> In this sample the high end spreads {r}× as much as the low end; with only 13 points per third, chance alone can give ratios up to about 1.6. Turn the percentage up.",
    t1NoteFanHtml: "<b>A fan: the sensor is about {tr}× noisier at x = 9 than at x = 2,</b> and in this sample the high end of the residuals spreads {r}× as much as the low end (chance moves that number around; draw a few samples). The fitted slope ({b}) is still about right; uneven scatter doesn't bias the line. What goes wrong is every statement about how uncertain it is. Trial 2 shows that.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "The error bars lie",
    t2Intro: "The experiment is repeated 400 times. Each time, the ordinary fit draws a 95% band where the next reading should land, and a 95% range for the slope. How often are they right?",
    t2PatLabel: "Where the sensor is worst",
    patHigh: "High readings",
    patEnds: "Both ends",
    t2PatHelp: "Both ends: the error is 0.5 in the middle of the range and grows toward each end, reaching the high-reading case's size at the edges.",
    t2BandAria: "One sample with the ordinary prediction band and 200 new readings at x = 2 and x = 9",
    t2BandCapHtml: "<b>One fit's 95% band, and 200 new readings at x = 2 and x = 9.</b> Red dots fall outside the band.",
    t2BarsAria: "How often each 95% promise held over 400 repeats",
    t2BarsCapHtml: "<b>How often each 95% promise held,</b> over 400 repeats. Dashed line: 95%.",
    barLow: "x=2 band",
    barHigh: "x=9 band",
    barSlopeDef: "slope",
    barSlopeRob: "robust slope",
    axCaught: "caught (%)",
    roPiLow: "Band catches new reading at x = 2",
    roPiHigh: "Band catches new reading at x = 9",
    roCiDef: "Slope range catches 2.00 (default)",
    roCiRob: "Slope range catches 2.00 (robust)",
    pctOf: "{p}%",
    t2NoteEvenHtml: "<b>With even scatter every promise holds:</b> about 95% everywhere.",
    t2NoteFanHtml: "<b>The band is one width everywhere, but the scatter isn't.</b> At x = 2 it catches {lo}% of new readings and at x = 9 {hi}%, against a promised 95%. Too wide wastes precision where readings are quiet; too narrow promises more than noisy readings can deliver. ",
    t2NoteSlopeBadHtml: "<b>The slope's default range is too narrow as well:</b> it catches 2.00 only {def}% of the time. Robust (HC3) standard errors fix that without changing the line: {rob}%.",
    t2NoteSlopeEndsMildHtml: "The slope's default range is only slightly narrow at this setting ({def}%); turn the error up and it gets worse. Robust (HC3) standard errors stay honest: {rob}%.",
    t2NoteSlopeOkHtml: "The slope's default range holds up here ({def}%): with the noise piled at one end, its errors happen to cancel. Switch to Both ends and they won't. Robust (HC3) standard errors are right either way: {rob}%.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "Weight each point by how much you trust it",
    t3Intro: "If you know each reading's uncertainty (from the datasheet or from repeat readings), a weighted fit gives each point a weight of 1/σ², so precise readings count more. Compare it with the ordinary fit.",
    t3MethodLabel: "Fit",
    mOls: "Ordinary",
    mWls: "Weighted (1/σ²)",
    t3DataAria: "Data with the chosen fit and its 95% prediction band",
    t3DataCapHtml: "<b>The chosen fit and its 95% band</b> for the next reading.",
    t3SpreadAria: "Spread of fitted slopes over 400 repeats for both methods",
    t3SpreadCapHtml: "<b>Fitted slopes from 400 repeats,</b> both methods. The narrower pile is the more precise method.",
    roOlsSd: "Slope scatter (SD), ordinary",
    roWlsSd: "Slope scatter (SD), weighted",
    roPiLow3: "Band catches new reading at x = 2",
    roPiHigh3: "Band catches new reading at x = 9",
    lblOls: "ordinary",
    lblWls: "weighted",
    axFittedSlope: "fitted slope",
    axRepeats: "repeats",
    t3NoteOlsHtml: "<b>The ordinary fit treats every point as equally trustworthy.</b> Its band has one width, so it misses at the noisy end. Switch to Weighted.",
    t3NoteWlsHtml: "<b>The weighted band widens where the sensor is worse,</b> and now catches about 95% at both ends ({lo}% and {hi}%). Its slope also scatters less from run to run (SD {w} against {o} for the ordinary fit), because it leans on the precise readings. The catch: you need a fair estimate of each reading's σ.",
    t3NoteEvenHtml: "<b>With even scatter, the two fits agree.</b> Weighting only helps when the points aren't equally trustworthy.",
    logSummary: "What about taking the log?",
    logBodyHtml: "If the error is <i>purely</i> a percentage of the reading and the physics is multiplicative (y = a·x<sup>b</sup>, or exponential growth or decay), fitting log y makes the scatter even. It also changes what the coefficients mean, and a fixed error part (the 0.5 here) comes back as uneven scatter at small readings. When you know σ for each point, weighting is the more direct fix.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>A fan in the residual plot means uneven scatter.</b> Check the shape first (Module 2): a curve can look like a fan.",
    take2Html: "<b>The line is still about right. The error bars aren't:</b> too wide where readings are quiet, too narrow where they're noisy.",
    take3Html: "<b>If you know each reading's σ, weight by 1/σ².</b> Your datasheet usually tells you. Otherwise, use robust (HC3) standard errors for honest slope ranges.",
    take4Html: "<b>Pooling two instruments or sessions</b> with different precision creates the same problem. Weight them, or fit them separately.",
    checkTitle: "How to do it",
    check1Title: "Excel",
    check1Body: "No weighted fit built in. Multiply each row's x, y and a column of 1s by √w, then use LINEST with no constant.",
    check2Title: "MATLAB",
    check2Body: "fitlm(x, y, 'Weights', 1./sigma.^2). Robust errors: hac(x, y, 'type', 'HC', 'weights', 'HC3') in the Econometrics Toolbox. (fitlm's 'RobustOpts' is something else: it downweights outliers.)",
    check3Title: "Python",
    check3Body: "statsmodels: sm.WLS(y, X, weights=1/sigma**2). Robust: .fit(cov_type='HC3'). scipy: curve_fit(..., sigma=sigma, absolute_sigma=True).",
    footNote: "Simulated data. True model y = 1 + 2x; sensor error SD = 0.5 + p% of the true reading.",
    footRead: "Further reading: Long and Ervin (2000), \"Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model\"; MacKinnon and White (1985), \"Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties\"; White (1980), \"A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity\"."
  },
  es: {
    pageTitle: "Dispersión desigual · Cómo leer tus ajustes de curvas",
    eyebrow: "Cómo leer tus ajustes de curvas · Módulo 3",
    h1: "Dispersión desigual",
    lead: "Muchos sensores especifican su error como un porcentaje de la lectura, así que las lecturas grandes traen errores grandes. La recta ajustada aguanta eso. Las barras de error, no.",
    introHtml: "Cuando la dispersión crece (o se achica) a lo largo del ajuste, la gráfica de residuos se abre en abanico. Los estadísticos llaman a esto <i>heterocedasticidad</i>: dispersión desigual. Aquí el error del sensor es de 0,5 unidades fijas más un porcentaje de la lectura, como lo indican muchas hojas de datos. Todos los datos se simulan a partir de y = 1 + 2x, así que la pendiente verdadera es <b>2,00</b>.",
    keyAria: "Leyenda de colores",
    keyTruth: "La verdad",
    keyFit: "Ajuste por mínimos cuadrados ordinarios y su banda",
    keyFix: "Ajuste ponderado y su banda",
    keyPts: "Puntos medidos",
    takeLabel: "Llévatelo:",
    takeSlides: "Diapositivas",
    takePy: "Script de Python",
    takePlay: "Juega con el código (en inglés)",
    takeColab: "Abrir en Colab (en inglés)",

    pctLabel: "Error del sensor, % de la lectura",
    pctHelp: "Más 0,5 unidades fijas. Las hojas de datos suelen decir \"±0,5 + 10% de la lectura\".",
    pctFmt: "{p}%",
    btnNewSample: "Generar datos nuevos",
    axX: "x",
    axY: "y medida",
    axFittedY: "y ajustada",
    axResidual: "residuo",

    // Trial 1
    t1Num: "Prueba 1 de 3",
    t1Title: "El abanico",
    t1Intro: "Sube la parte porcentual del error del sensor y mira la gráfica de residuos.",
    roSlope: "Pendiente ajustada",
    roTrue: "Pendiente verdadera",
    roLow: "Dispersión de los residuos, tercio bajo",
    roHigh: "Dispersión de los residuos, tercio alto",
    roRatio: "Alto ÷ bajo",
    ratioFmt: "{r}×",
    t1DataAria: "Datos con la recta ajustada y la verdadera",
    t1DataCapHtml: "<b>Los datos y el ajuste.</b> 40 lecturas.",
    t1ResidAria: "Residuos contra el valor ajustado",
    t1ResidCapHtml: "<b>Gráfica de residuos.</b> La dispersión se mide como la desviación estándar de los residuos en el tercio más bajo y en el más alto de los valores ajustados.",
    t1NoteEvenHtml: "<b>Con este valor, la dispersión es más o menos pareja.</b> En esta muestra, el extremo alto se dispersa {r}× lo que el bajo; con solo 13 puntos por tercio, el puro azar puede dar cocientes de hasta más o menos 1,6. Sube el porcentaje.",
    t1NoteFanHtml: "<b>Un abanico: el sensor tiene unas {tr}× más ruido en x = 9 que en x = 2,</b> y en esta muestra el extremo alto de los residuos se dispersa {r}× lo que el bajo (el azar mueve ese número; genera datos nuevos unas cuantas veces). La pendiente ajustada ({b}) sigue siendo más o menos correcta: la dispersión desigual no sesga la recta. Lo que falla es todo lo que se dice sobre su incertidumbre. La Prueba 2 lo muestra.",

    // Trial 2
    t2Num: "Prueba 2 de 3",
    t2Title: "Las barras de error mienten",
    t2Intro: "El experimento se repite 400 veces. Cada vez, el ajuste ordinario dibuja una banda del 95% donde debería caer la siguiente lectura, y un intervalo del 95% para la pendiente. ¿Qué tan seguido aciertan?",
    t2PatLabel: "Dónde es peor el sensor",
    patHigh: "Lecturas altas",
    patEnds: "Ambos extremos",
    t2PatHelp: "Ambos extremos: el error es 0,5 en el centro del rango y crece hacia cada extremo, hasta llegar en los bordes al tamaño del caso de lecturas altas.",
    t2BandAria: "Una muestra con la banda de predicción ordinaria y 200 lecturas nuevas en x = 2 y x = 9",
    t2BandCapHtml: "<b>La banda del 95% de un ajuste, y 200 lecturas nuevas en x = 2 y x = 9.</b> Los puntos rojos caen fuera de la banda.",
    t2BarsAria: "Qué tan seguido se cumplió cada promesa del 95% en 400 repeticiones",
    t2BarsCapHtml: "<b>Qué tan seguido se cumplió cada promesa del 95%,</b> en 400 repeticiones. Línea discontinua: 95%.",
    barLow: "banda x=2",
    barHigh: "banda x=9",
    barSlopeDef: "pendiente",
    barSlopeRob: "robusta",
    axCaught: "aciertos (%)",
    roPiLow: "La banda contiene la nueva lectura en x\u00A0=\u00A02",
    roPiHigh: "La banda contiene la nueva lectura en x\u00A0=\u00A09",
    roCiDef: "El intervalo de la pendiente contiene 2,00 (por\u00A0defecto)",
    roCiRob: "El intervalo de la pendiente contiene 2,00 (robusto)",
    pctOf: "{p}%",
    t2NoteEvenHtml: "<b>Con dispersión pareja, todas las promesas se cumplen:</b> alrededor del 95% en todas partes.",
    t2NoteFanHtml: "<b>La banda tiene el mismo ancho en todas partes, pero la dispersión no.</b> En x = 2 contiene el {lo}% de las lecturas nuevas y en x = 9, el {hi}%, frente al 95% prometido. Una banda demasiado ancha desperdicia precisión donde las lecturas son tranquilas; una demasiado angosta promete más de lo que pueden cumplir las lecturas ruidosas. ",
    t2NoteSlopeBadHtml: "<b>El intervalo por defecto de la pendiente también es demasiado angosto:</b> contiene el 2,00 solo el {def}% de las veces. Los errores estándar robustos (HC3) lo corrigen sin cambiar la recta: {rob}%.",
    t2NoteSlopeEndsMildHtml: "Con este valor, el intervalo por defecto de la pendiente es apenas un poco angosto ({def}%); sube el error y empeora. Los errores estándar robustos (HC3) siguen siendo honestos: {rob}%.",
    t2NoteSlopeOkHtml: "Aquí el intervalo por defecto de la pendiente aguanta ({def}%): con el ruido amontonado en un extremo, sus errores se cancelan por casualidad. Cambia a Ambos extremos y ya no se cancelarán. Los errores estándar robustos (HC3) son correctos en los dos casos: {rob}%.",

    // Trial 3
    t3Num: "Prueba 3 de 3",
    t3Title: "Pondera cada punto según cuánto confías en él",
    t3Intro: "Si conoces la incertidumbre de cada lectura (por la hoja de datos o por lecturas repetidas), un ajuste ponderado le da a cada punto un peso de 1/σ², así que las lecturas precisas cuentan más. Compáralo con el ajuste ordinario.",
    t3MethodLabel: "Ajuste",
    mOls: "Ordinario",
    mWls: "Ponderado (1/σ²)",
    t3DataAria: "Datos con el ajuste elegido y su banda de predicción del 95%",
    t3DataCapHtml: "<b>El ajuste elegido y su banda del 95%</b> para la siguiente lectura.",
    t3SpreadAria: "Dispersión de las pendientes ajustadas en 400 repeticiones, con los dos métodos",
    t3SpreadCapHtml: "<b>Pendientes ajustadas en 400 repeticiones,</b> con los dos métodos. El montón más angosto es el del método más preciso.",
    roOlsSd: "Dispersión de la pendiente (desv. est.), ordinario",
    roWlsSd: "Dispersión de la pendiente (desv. est.), ponderado",
    roPiLow3: "La banda contiene la nueva lectura en x\u00A0=\u00A02",
    roPiHigh3: "La banda contiene la nueva lectura en x\u00A0=\u00A09",
    lblOls: "ordinario",
    lblWls: "ponderado",
    axFittedSlope: "pendiente ajustada",
    axRepeats: "repeticiones",
    t3NoteOlsHtml: "<b>El ajuste ordinario trata todos los puntos como igual de confiables.</b> Su banda tiene un solo ancho, así que falla en el extremo ruidoso. Cambia a Ponderado.",
    t3NoteWlsHtml: "<b>La banda ponderada se ensancha donde el sensor es peor</b> y ahora contiene alrededor del 95% en los dos extremos ({lo}% y {hi}%). Su pendiente también varía menos de una repetición a otra (desv. est. {w} frente a {o} del ajuste ordinario), porque se apoya en las lecturas precisas. El inconveniente: necesitas una estimación razonable de la σ de cada lectura.",
    t3NoteEvenHtml: "<b>Con dispersión pareja, los dos ajustes coinciden.</b> Ponderar solo ayuda cuando los puntos no son igual de confiables.",
    logSummary: "¿Y si saco el logaritmo?",
    logBodyHtml: "Si el error es <i>solo</i> un porcentaje de la lectura y la física es multiplicativa (y = a·x<sup>b</sup>, o un crecimiento o decaimiento exponencial), ajustar log y empareja la dispersión. También cambia lo que significan los coeficientes, y una parte fija del error (el 0,5 de aquí) vuelve a aparecer como dispersión desigual en las lecturas pequeñas. Cuando conoces la σ de cada punto, ponderar es la solución más directa.",

    // Takeaways
    takeTitle: "Para recordar",
    take1Html: "<b>Un abanico en la gráfica de residuos significa dispersión desigual.</b> Revisa primero la forma (Módulo 2): una curva puede parecer un abanico.",
    take2Html: "<b>La recta sigue siendo más o menos correcta. Las barras de error, no:</b> demasiado anchas donde las lecturas son tranquilas y demasiado angostas donde son ruidosas.",
    take3Html: "<b>Si conoces la σ de cada lectura, pondera con 1/σ².</b> Tu hoja de datos casi siempre te la da. Si no, usa errores estándar robustos (HC3) para tener intervalos honestos para la pendiente.",
    take4Html: "<b>Juntar dos instrumentos o dos sesiones</b> con distinta precisión crea el mismo problema. Pondéralos o ajústalos por separado.",
    checkTitle: "Cómo hacerlo",
    check1Title: "Excel",
    check1Body: "No trae un ajuste ponderado. Multiplica por √w la x, la y y una columna de unos de cada fila, y luego usa ESTIMACION.LINEAL (LINEST en Excel en inglés) sin constante.",
    check2Title: "MATLAB",
    check2Body: "fitlm(x, y, 'Weights', 1./sigma.^2). Errores robustos: hac(x, y, 'type', 'HC', 'weights', 'HC3') en la Econometrics Toolbox. (La opción 'RobustOpts' de fitlm es otra cosa: les quita peso a los valores atípicos).",
    check3Title: "Python",
    check3Body: "statsmodels: sm.WLS(y, X, weights=1/sigma**2). Robustos: .fit(cov_type='HC3'). scipy: curve_fit(..., sigma=sigma, absolute_sigma=True).",
    footNote: "Datos simulados. Modelo verdadero y = 1 + 2x; desviación estándar del error del sensor = 0,5 + p% de la lectura verdadera.",
    footRead: "Lecturas recomendadas: Long y Ervin (2000), \"Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model\"; MacKinnon y White (1985), \"Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties\"; White (1980), \"A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity\"."
  },
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "HC3", es: "HC3" }, href: "https://doi.org/10.1080/00031305.2000.10474549" },
    { phrase: { en: "\"Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model\"", es: "\"Using Heteroscedasticity Consistent Standard Errors in the Linear Regression Model\"" }, href: "https://doi.org/10.1080/00031305.2000.10474549" },
    { phrase: { en: "\"Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties\"", es: "\"Some Heteroskedasticity-Consistent Covariance Matrix Estimators with Improved Finite Sample Properties\"" }, href: "https://doi.org/10.1016/0304-4076(85)90158-7" },
    { phrase: { en: "\"A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity\"", es: "\"A Heteroskedasticity-Consistent Covariance Matrix Estimator and a Direct Test for Heteroskedasticity\"" }, href: "https://doi.org/10.2307/1912934" }
  ]
};
