// strings.js — Why R² isn't enough (Reading Your Fits, Module 1).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Why R² Isn't Enough · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 1",
    h1: "Why R² Isn't Enough",
    lead: "R² is the number everyone reports and almost nobody should trust on its own. It can't tell a good fit from a bad one, it rises when you test a wider range, and it always goes up when you add terms.",
    introHtml: "<b>R²</b> is the share of the scatter in y that the fitted line accounts for: 1 means every point sits on the line, 0 means the line explains nothing. Excel's trendline shows it by default. This module shows three ways it misleads. Trials 2 and 3 use simulated data with a known true line.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The fitted line or curve",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "Four datasets, one R²",
    t1Intro: "These four small datasets were built by the statistician Francis Anscombe in 1973. Each has 11 points. Flip between them and watch the readouts.",
    t1SetLabel: "Dataset",
    roSlope: "Slope",
    roIntercept: "Intercept",
    roR2: "R²",
    roS: "Residual SD",
    t1DataAria: "The selected dataset with its fitted line",
    t1DataCapHtml: "<b>The data and the fit.</b>",
    t1ResidAria: "Residuals against fitted value for the selected dataset",
    t1ResidCapHtml: "<b>Residual plot.</b> The leftovers after the fit.",
    axX: "x",
    axY: "y",
    axFittedY: "fitted y",
    axResidual: "residual",
    t1Note1Html: "<b>Dataset I is what a line fit is for:</b> a straight trend with even scatter. The residuals are a shapeless band.",
    t1Note2Html: "<b>Dataset II is a smooth curve.</b> The line is the wrong shape, and the residuals form an upside-down U. A quadratic would fit it almost exactly.",
    t1Note3Html: "<b>Dataset III is a perfect line with one bad point.</b> That single point tilts the fit and drags R² down from nearly 1. One residual stands far from the rest.",
    t1Note4Html: "<b>Dataset IV isn't a trend at all.</b> Ten points share one x value; one point far out sets the whole slope. Remove it and there's no slope left to measure.",
    t1Same: "Same slope, same intercept, same R² for all four, to two decimal places.",
    quizPromptHtml: "<b>Now that you've seen all four:</b> for which one can you trust the fitted line as it stands?",
    quizAria: "Your answer",
    quizRightHtml: "<b>Right: only dataset I.</b> ",
    quizWrongHtml: "<b>Only dataset I.</b> ",
    quizExplain: "III is a straight line too, but one bad point has tilted the fit, so you'd check or explain that point first. II needs a curve, and IV has no trend to fit. All four report R² = 0.67, the same line and the same residual SD. The number can't tell them apart; the plots can.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "R² measures your test range",
    t2Intro: "Same sensor, same noise, same true slope. The only thing you change is how wide a range of x you test over.",
    t2SpanLabel: "Range of x tested",
    spanFmt: "0 to {s}",
    t2NoiseLabel: "Sensor noise (SD)",
    t2NoiseHelp: "Standard deviation of the y sensor's error, in y units.",
    btnNewSample: "Draw a new sample",
    roSlopeCi: "Slope (95% range)",
    ciFmt: "{b} ± {h}",
    roExpected: "R² with unlimited data",
    t2DataAria: "Data and fitted line over the tested range",
    t2DataCapHtml: "<b>The data and the fit.</b> 30 readings spread evenly over the tested range.",
    t2CurveAria: "Expected R² against the range of x tested",
    t2CurveCapHtml: "<b>R² you'd get with unlimited data at each test range,</b> for this noise level. Small samples scatter around it. The dot is your current setting.",
    axXRange: "range of x tested (0 to …)",
    axExpectedR2: "R² with unlimited data",
    t2NoteHtml: "<b>R² is {r2}, and the residual SD is {s}.</b> Slide the range: R² climbs toward 1 as the range widens and sinks as it narrows, while the residual SD stays near {sd}, the sensor's noise. R² is partly a measure of your test plan. The residual SD, in real units, tells someone how far off a single reading can be.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "More terms always raise R²",
    t3Intro: "Twelve readings from a straight line plus noise. Add polynomial terms (x², x³, …) one at a time and watch R² and the curve.",
    t3DegLabel: "Polynomial degree",
    t3DegHelp: "1 is a straight line, the true shape here.",
    roAdjR2: "Adjusted R²",
    roLoo: "Error on a point it hasn't seen",
    roPred: "Prediction at x = 12 (truth 25)",
    t3DataAria: "Twelve readings with the polynomial fit and a prediction beyond the data",
    t3DataCapHtml: "<b>The fit, and past the data.</b> The shaded strip is beyond the last reading.",
    t3LooAria: "Error on unseen points for each polynomial degree",
    t3LooCapHtml: "<b>Error on a point the fit hasn't seen,</b> for each degree: leave one point out, fit the rest, predict it, repeat. Dashed line: the sensor noise. Values past the top are drawn at the edge.",
    axDegree: "polynomial degree",
    axLoo: "error on unseen point (RMS)",
    lblNoise: "sensor noise",
    lblBeyond: "beyond the data",
    t3Note1Html: "<b>Degree 1, the true shape.</b> R² is {r2}. Now add terms and watch it creep up.",
    t3NoteSomeHtml: "<b>R² rose to {r2}, but the curve is only bending to chase this sample's noise.</b> The error on a point the fit hasn't seen went from {loo1} for the straight line to {loo} now: no real gain. Adjusted R² charges for each extra term; it's {adj} here.",
    t3NoteManyHtml: "<b>R² is up to {r2}, and the curve is getting worse, not better.</b> It bends to thread through the points, so its error on a point it hasn't seen jumps to {loo}, and just past the data it predicts {pred} where the truth is 25. More terms always raise R². They rarely raise the truth.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>R² can't tell a good fit from a bad one.</b> Four very different datasets share R² = 0.67. Look at the data and the residuals.",
    take2Html: "<b>R² depends on how wide a range you tested.</b> Report the residual SD in real units alongside it (or instead of it).",
    take3Html: "<b>Adding terms always raises R².</b> Choose the model from the physics, then check it with residual plots and error on unseen points.",
    take4Html: "<b>A high R² is not a pass mark.</b> A calibration with R² = 0.999 can still have curved residuals and a wrong shape (Module 2).",
    checkTitle: "What to report instead",
    check1Title: "The residual SD",
    check1Body: "In real units: how far a single reading typically sits from the line.",
    check2Title: "The residual plots",
    check2Body: "Against the fitted value and in run order. Module 2 shows what to look for.",
    check3Title: "A range on the slope",
    check3Body: "The slope with its 95% range, not just the number. Module 6 covers the rest.",
    footNote: "Trial 1: Anscombe (1973), \"Graphs in Statistical Analysis\", The American Statistician 27(1). Trials 2 and 3: simulated, y = 1 + 2x + error."
  },
  es: {
    pageTitle: "Por qué R² no basta · Cómo leer tus ajustes de curvas",
    eyebrow: "Cómo leer tus ajustes de curvas · Módulo 1",
    h1: "Por qué R² no basta",
    lead: "R² es el número que todos reportan y en el que casi nadie debería confiar por sí solo. No distingue un buen ajuste de uno malo, sube cuando pruebas un rango más amplio y siempre aumenta cuando agregas términos.",
    introHtml: "<b>R²</b> es la parte de la dispersión en y que explica la recta ajustada: 1 significa que todos los puntos caen sobre la recta; 0, que la recta no explica nada. La línea de tendencia de Excel lo muestra por defecto. Este módulo muestra tres formas en que engaña. Las Pruebas 2 y 3 usan datos simulados con una recta verdadera conocida.",
    keyAria: "Leyenda de colores",
    keyTruth: "La verdad",
    keyFit: "La recta o curva ajustada",
    keyPts: "Puntos medidos",
    takeLabel: "Llévatelo:",
    takeSlides: "Diapositivas",
    takePy: "Script de Python",

    // Trial 1
    t1Num: "Prueba 1 de 3",
    t1Title: "Cuatro conjuntos de datos, un solo R²",
    t1Intro: "Estos cuatro pequeños conjuntos de datos los construyó el estadístico Francis Anscombe en 1973. Cada uno tiene 11 puntos. Cambia de uno a otro y mira los resultados.",
    t1SetLabel: "Conjunto de datos",
    roSlope: "Pendiente",
    roIntercept: "Ordenada al origen",
    roR2: "R²",
    roS: "Desv. estándar de los residuos",
    t1DataAria: "El conjunto de datos elegido con su recta ajustada",
    t1DataCapHtml: "<b>Los datos y el ajuste.</b>",
    t1ResidAria: "Residuos contra el valor ajustado del conjunto elegido",
    t1ResidCapHtml: "<b>Gráfica de residuos.</b> Lo que sobra después del ajuste.",
    axX: "x",
    axY: "y",
    axFittedY: "y ajustada",
    axResidual: "residuo",
    t1Note1Html: "<b>El conjunto I es para lo que sirve ajustar una recta:</b> una tendencia recta con dispersión pareja. Los residuos forman una banda sin forma.",
    t1Note2Html: "<b>El conjunto II es una curva suave.</b> La recta tiene la forma equivocada, y los residuos forman una U invertida. Una parábola lo ajustaría casi exactamente.",
    t1Note3Html: "<b>El conjunto III es una recta perfecta con un punto malo.</b> Ese único punto inclina el ajuste y baja R² desde casi 1. Un residuo queda muy lejos del resto.",
    t1Note4Html: "<b>El conjunto IV no es una tendencia.</b> Diez puntos comparten el mismo valor de x; un punto muy alejado fija toda la pendiente. Quítalo y ya no queda ninguna pendiente que medir.",
    t1Same: "La misma pendiente, la misma ordenada al origen y el mismo R² en los cuatro, con dos decimales.",
    quizPromptHtml: "<b>Ahora que viste los cuatro:</b> ¿en cuál puedes confiar en la recta ajustada tal como está?",
    quizAria: "Tu respuesta",
    quizRightHtml: "<b>Correcto: solo en el conjunto I.</b> ",
    quizWrongHtml: "<b>Solo en el conjunto I.</b> ",
    quizExplain: "El III también es una recta, pero un punto malo inclinó el ajuste, así que primero tendrías que revisar o explicar ese punto. El II necesita una curva, y el IV no tiene ninguna tendencia que ajustar. Los cuatro dan R² = 0,67, la misma recta y la misma desviación estándar de los residuos. El número no los distingue; las gráficas sí.",

    // Trial 2
    t2Num: "Prueba 2 de 3",
    t2Title: "R² mide tu rango de prueba",
    t2Intro: "El mismo sensor, el mismo ruido, la misma pendiente verdadera. Lo único que cambias es qué tan amplio es el rango de x en el que pruebas.",
    t2SpanLabel: "Rango de x probado",
    spanFmt: "0 a {s}",
    t2NoiseLabel: "Ruido del sensor (desv. est.)",
    t2NoiseHelp: "Desviación estándar del error del sensor de y, en unidades de y.",
    btnNewSample: "Generar datos nuevos",
    roSlopeCi: "Pendiente (intervalo del 95%)",
    ciFmt: "{b} ± {h}",
    roExpected: "R² con datos ilimitados",
    t2DataAria: "Datos y recta ajustada en el rango probado",
    t2DataCapHtml: "<b>Los datos y el ajuste.</b> 30 lecturas repartidas de forma pareja en el rango probado.",
    t2CurveAria: "R² esperado contra el rango de x probado",
    t2CurveCapHtml: "<b>El R² que obtendrías con datos ilimitados en cada rango de prueba,</b> para este nivel de ruido. Las muestras pequeñas se dispersan alrededor de él. El punto es tu configuración actual.",
    axXRange: "rango de x probado (0 a …)",
    axExpectedR2: "R² con datos ilimitados",
    t2NoteHtml: "<b>R² es {r2}, y la desviación estándar de los residuos es {s}.</b> Mueve el rango: R² sube hacia 1 cuando el rango se amplía y baja cuando se angosta, mientras que la desviación estándar de los residuos se queda cerca de {sd}, el ruido del sensor. R² es en parte una medida de tu plan de pruebas. La desviación estándar de los residuos, en unidades reales, le dice a cualquiera qué tan lejos puede quedar una sola lectura.",

    // Trial 3
    t3Num: "Prueba 3 de 3",
    t3Title: "Más términos siempre suben R²",
    t3Intro: "Doce lecturas de una recta más ruido. Agrega términos polinómicos (x², x³, …) de uno en uno y mira R² y la curva.",
    t3DegLabel: "Grado del polinomio",
    t3DegHelp: "1 es una recta, la forma verdadera aquí.",
    roAdjR2: "R² ajustado",
    roLoo: "Error en un punto que no vio",
    roPred: "Predicción en x = 12 (verdad: 25)",
    t3DataAria: "Doce lecturas con el ajuste polinómico y una predicción más allá de los datos",
    t3DataCapHtml: "<b>El ajuste, y más allá de los datos.</b> La franja sombreada está después de la última lectura.",
    t3LooAria: "Error en puntos no vistos para cada grado del polinomio",
    t3LooCapHtml: "<b>Error en un punto que el ajuste no vio,</b> para cada grado: deja un punto fuera, ajusta el resto, predícelo y repite. Línea discontinua: el ruido del sensor. Los valores que se salen por arriba se dibujan en el borde.",
    axDegree: "grado del polinomio",
    axLoo: "error en un punto no visto (RMS)",
    lblNoise: "ruido del sensor",
    lblBeyond: "más allá de los datos",
    t3Note1Html: "<b>Grado 1, la forma verdadera.</b> R² es {r2}. Ahora agrega términos y mira cómo va subiendo.",
    t3NoteSomeHtml: "<b>R² subió a {r2}, pero la curva solo se está doblando para perseguir el ruido de esta muestra.</b> El error en un punto que el ajuste no vio pasó de {loo1} con la recta a {loo} ahora: ninguna mejora real. El R² ajustado cobra por cada término extra; aquí vale {adj}.",
    t3NoteManyHtml: "<b>R² ya llegó a {r2}, y la curva está empeorando, no mejorando.</b> Se dobla para pasar por todos los puntos, así que su error en un punto que no vio salta a {loo}, y justo después de los datos predice {pred} donde la verdad es 25. Más términos siempre suben R². Rara vez te acercan a la verdad.",

    // Takeaways
    takeTitle: "Para recordar",
    take1Html: "<b>R² no distingue un buen ajuste de uno malo.</b> Cuatro conjuntos de datos muy distintos comparten R² = 0,67. Mira los datos y los residuos.",
    take2Html: "<b>R² depende de qué tan amplio fue el rango que probaste.</b> Reporta junto a él (o en su lugar) la desviación estándar de los residuos, en unidades reales.",
    take3Html: "<b>Agregar términos siempre sube R².</b> Elige el modelo a partir de la física y luego revísalo con gráficas de residuos y con el error en puntos no vistos.",
    take4Html: "<b>Un R² alto no es una nota aprobatoria.</b> Una calibración con R² = 0,999 puede tener residuos curvos y la forma equivocada (Módulo 2).",
    checkTitle: "Qué reportar en su lugar",
    check1Title: "La desviación estándar de los residuos",
    check1Body: "En unidades reales: qué tan lejos de la recta suele quedar una sola lectura.",
    check2Title: "Las gráficas de residuos",
    check2Body: "Contra el valor ajustado y en orden de medición. El Módulo 2 muestra qué buscar.",
    check3Title: "Un intervalo para la pendiente",
    check3Body: "La pendiente con su intervalo de confianza del 95%, no solo el número. El Módulo 6 cubre el resto.",
    footNote: "Prueba 1: Anscombe (1973), \"Graphs in Statistical Analysis\", The American Statistician 27(1). Pruebas 2 y 3: simuladas, y = 1 + 2x + error."
  },
  // Reference chips (see learning-i18n.js): the name opens the paper, the cited title its DOI.
  chips: [
    { phrase: { en: "Francis Anscombe", es: "Francis Anscombe" }, href: "https://doi.org/10.1080/00031305.1973.10478966" },
    { phrase: { en: "\"Graphs in Statistical Analysis\"", es: "\"Graphs in Statistical Analysis\"" }, href: "https://doi.org/10.1080/00031305.1973.10478966" }
  ]
};
