// strings.js — Why R² isn't enough (Reading Your Fits, Module 1).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js. `es` is filled in during the Spanish pass.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Why R² Isn't Enough · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 1",
    h1: "Why R² Isn't Enough",
    lead: "R² is the number everyone reports and almost nobody should trust on its own. It can't tell a good fit from a bad one, it rises when you test a wider range, and it always goes up when you add terms.",
    introHtml: "<b>R²</b> is the share of the scatter in y that the fitted line accounts for: 1 means every point sits on the line, 0 means the line explains nothing. Excel's trendline shows it by default. This module shows three ways it misleads. Trials 2 and 3 use simulated data with a known true line.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The fitted line or curve",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "Four datasets, one R²",
    t1Intro: "These four small datasets were built by the statistician Francis Anscombe in 1973. Each has 11 points. Flip between them and watch the readouts.",
    t1SetLabel: "Dataset",
    roSlope: "Slope",
    roIntercept: "Intercept",
    roR2: "R²",
    roS: "Residual SD",
    t1DataAria: "The selected dataset with its fitted line",
    t1DataCapHtml: "<b>The data and the fit.</b>",
    t1ResidAria: "Residuals against fitted value for the selected dataset",
    t1ResidCapHtml: "<b>Residual plot.</b> The leftovers after the fit.",
    axX: "x",
    axY: "y",
    axFittedY: "fitted y",
    axResidual: "residual",
    t1Note1Html: "<b>Dataset I is what a line fit is for:</b> a straight trend with even scatter. The residuals are a shapeless band.",
    t1Note2Html: "<b>Dataset II is a smooth curve.</b> The line is the wrong shape, and the residuals form an upside-down U. A quadratic would fit it almost exactly.",
    t1Note3Html: "<b>Dataset III is a perfect line with one bad point.</b> That single point tilts the fit and drags R² down from nearly 1. One residual stands far from the rest.",
    t1Note4Html: "<b>Dataset IV isn't a trend at all.</b> Ten points share one x value; one point far out sets the whole slope. Remove it and there's no slope left to measure.",
    t1Same: "Same slope, same intercept, same R² for all four, to two decimal places.",
    quizPromptHtml: "<b>Now that you've seen all four:</b> for which one is a straight-line fit the right model?",
    quizAria: "Your answer",
    quizRightHtml: "<b>Right: only dataset I.</b> ",
    quizWrongHtml: "<b>Only dataset I.</b> ",
    quizExplain: "All four report R² = 0.67, the same line and the same residual SD. The number can't tell them apart; the plots can. Always look at the data and the residuals before you trust R².",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "R² measures your test range",
    t2Intro: "Same sensor, same noise, same true slope. The only thing you change is how wide a range of x you test over.",
    t2SpanLabel: "Range of x tested",
    spanFmt: "0 to {s}",
    t2NoiseLabel: "Sensor noise (SD)",
    t2NoiseHelp: "Standard deviation of the y sensor's error, in y units.",
    btnNewSample: "Draw a new sample",
    roSlopeCi: "Slope (95% range)",
    ciFmt: "{b} ± {h}",
    roExpected: "R² expected on average",
    t2DataAria: "Data and fitted line over the tested range",
    t2DataCapHtml: "<b>The data and the fit.</b> 30 readings spread evenly over the tested range.",
    t2CurveAria: "Expected R² against the range of x tested",
    t2CurveCapHtml: "<b>R² you'd expect at each test range,</b> for this noise level. The dot is your current setting.",
    axXRange: "range of x tested (0 to …)",
    axExpectedR2: "expected R²",
    t2NoteHtml: "<b>R² is {r2}, and the residual SD is {s}.</b> Slide the range: R² climbs toward 1 as the range widens and sinks as it narrows, while the residual SD stays near {sd}, the sensor's noise. R² is partly a measure of your test plan. The residual SD, in real units, tells someone how far off a single reading can be.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "More terms always raise R²",
    t3Intro: "Twelve readings from a straight line plus noise. Add polynomial terms (x², x³, …) one at a time and watch R² and the curve.",
    t3DegLabel: "Polynomial degree",
    t3DegHelp: "1 is a straight line, the true shape here.",
    roAdjR2: "Adjusted R²",
    roLoo: "Error on a point it hasn't seen",
    roPred: "Prediction at x = 12 (truth 25)",
    t3DataAria: "Twelve readings with the polynomial fit and a prediction beyond the data",
    t3DataCapHtml: "<b>The fit, and past the data.</b> The shaded strip is beyond the last reading.",
    t3LooAria: "Error on unseen points for each polynomial degree",
    t3LooCapHtml: "<b>Error on a point the fit hasn't seen,</b> for each degree: leave one point out, fit the rest, predict it, repeat. Dashed line: the sensor noise. Values past the top are drawn at the edge.",
    axDegree: "polynomial degree",
    axLoo: "error on unseen point (RMS)",
    lblNoise: "sensor noise",
    lblBeyond: "beyond the data",
    t3Note1Html: "<b>Degree 1, the true shape.</b> R² is {r2}. Now add terms and watch it creep up.",
    t3NoteSomeHtml: "<b>R² rose to {r2}, but the curve is only bending to chase this sample's noise.</b> The error on a point the fit hasn't seen went from {loo1} for the straight line to {loo} now: no real gain. Adjusted R² charges for each extra term; it's {adj} here.",
    t3NoteManyHtml: "<b>R² is up to {r2}, and the curve is getting worse, not better.</b> It bends to thread through the points, so its error on a point it hasn't seen jumps to {loo}, and just past the data it predicts {pred} where the truth is 25. More terms always raise R². They rarely raise the truth.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>R² can't tell a good fit from a bad one.</b> Four very different datasets share R² = 0.67. Look at the data and the residuals.",
    take2Html: "<b>R² depends on how wide a range you tested.</b> Report the residual SD in real units alongside it (or instead of it).",
    take3Html: "<b>Adding terms always raises R².</b> Choose the model from the physics, then check it with residual plots and error on unseen points.",
    take4Html: "<b>A high R² is not a pass mark.</b> A calibration with R² = 0.999 can still have curved residuals and a wrong shape (Module 2).",
    checkTitle: "What to report instead",
    check1Title: "The residual SD",
    check1Body: "In real units: how far a single reading typically sits from the line.",
    check2Title: "The residual plots",
    check2Body: "Against the fitted value and in run order. Module 2 shows what to look for.",
    check3Title: "A range on the slope",
    check3Body: "The slope with its 95% range, not just the number. Module 6 covers the rest.",
    footNote: "Trial 1: Anscombe (1973), \"Graphs in Statistical Analysis\", The American Statistician 27(1). Trials 2 and 3: simulated, y = 1 + 2x + error."
  },
  es: {}
};
