// strings.js — Using and reporting a fit (Reading Your Fits, Module 6).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Using and Reporting a Fit · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 6",
    h1: "Using and Reporting a Fit",
    lead: "Once the checks pass, the fit is a tool: for predicting a reading, estimating a constant, or computing something from the coefficients. Each use needs its own kind of error bar.",
    introHtml: "This module covers the two bands every fit comes with, how to carry the fit's uncertainty into a number you compute from it, and what to write down. All data is simulated from y = 1 + 2x with sensor noise SD 2 unless a trial says otherwise.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The fit, and the band for the line itself",
    keyFix: "A second method for comparison",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    btnNewSample: "Draw a new sample",
    pmFmt: "± {h}",
    yes: "yes",
    no: "no",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "Two bands: the line, and the next reading",
    t1Intro: "Fifteen readings over x = 0 to 10. Slide the point where you want an answer, including past the data.",
    t1XLabel: "Where you want a prediction (x)",
    roYhat: "Fitted y there",
    roCi: "Where the true line is (95%)",
    roPi: "Where the next reading will land (95%)",
    roInside: "Inside the tested range?",
    t1DataAria: "Data, fitted line, confidence band and prediction band",
    t1DataCapHtml: "<b>Red band: where the true line is. Grey band: where a new reading will land.</b> The shaded strips are outside the tested range.",
    t1WidthAria: "Half-width of both bands along x",
    t1WidthCapHtml: "<b>How wide each band is along x.</b> Both are narrowest in the middle of the data and flare outward.",
    axX: "x",
    axY: "y",
    axHalf: "half-width of the 95% band",
    lblCi: "true line",
    lblPi: "next reading",
    lblOutside: "outside the data",
    t1NoteInHtml: "<b>Inside the data, the answer depends on the question.</b> The true line is within ±{ci} of {y}. A single new reading will land within ±{pi}: wider, because it carries the sensor's own noise on top of the line's uncertainty, and that part never shrinks with more data.",
    t1NoteOutHtml: "<b>You're {d} units past the data.</b> Both bands have flared (±{ci} for the line, ±{pi} for a reading), and that's the <i>optimistic</i> version: it assumes the straight line still holds out here. Nothing in the data can confirm that. Extrapolate only as far as the physics lets you.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "Carrying the uncertainty into a result",
    t2Intro: "Often the answer isn't a coefficient but something computed from both: here, the x where the line crosses zero (like the temperature where a sensor's output crosses 0 V). The intercept b0 is the fit's value at x = 0, which may be far from where you took data.",
    t2DLabel: "How far the data sit from x = 0",
    t2DHelp: "The data span 5 units starting here. The true line crosses zero at the left edge of the data.",
    roCross: "Estimated crossing",
    roTrueCross: "True crossing",
    roNaive: "95% range, ignoring correlation",
    roDelta: "95% range, with correlation",
    roBoot: "95% range, bootstrap",
    roActual: "Actual spread over 400 repeats",
    t2DataAria: "Data and fitted line extended back to where it crosses zero, with two error bars on the crossing",
    t2DataCapHtml: "<b>The fit, extended back to where it crosses zero.</b> Red bar: range ignoring correlation. Blue bar: range with it.",
    t2HistAria: "Crossings from 400 repeated experiments with both ranges marked",
    t2HistCapHtml: "<b>Crossings from 400 repeats of the experiment.</b> A good 95% range should span about the middle 95% of this pile.",
    axCross: "estimated crossing (x)",
    axRepeats: "repeats",
    lblNaive: "ignoring correlation",
    lblDelta: "with correlation",
    t2NoteHtml: "<b>Ignoring how the slope and intercept move together gives ±{n}; accounting for it gives ±{d}.</b> The farther the data sit from x = 0, the worse the first method gets. The repeats actually spread ±{a}, and a bootstrap from this one dataset gives ±{b}, close to it (it varies from sample to sample). The intercept and slope are estimated from the same points, so when one comes out high the other comes out low. Use the full covariance (the <i>delta method</i>) or a bootstrap, never the two standard errors on their own.",
    t2NoteNearHtml: "<b>With the data near x = 0, the two methods nearly agree</b> (±{n} and ±{d}; actual ±{a}). Slide the data away from zero and watch them part.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "What to write down",
    t3Intro: "A report line built from Trial 1's data. Copy it into a lab report and fill in the parts only you can check.",
    t3ReportLabel: "Report text",
    btnCopy: "Copy",
    copied: "Copied",
    copyFail: "Select the text and copy it",
    reportTpl: "Linear least-squares fit, y = b0 + b1·x, n = {n} readings over x = {xlo} to {xhi}.\nSlope b1 = {b1} ± {b1h} (95% range); intercept b0 = {b0} ± {b0h}.\nResidual SD s = {s} (in y's units): a typical reading sits this far from the line.\nPrediction at x = {x0}: {yhat} ± {pih} for a single new reading (95%){outside}.\nResidual checks: [against fitted value: ___ ] [in run order: ___ ] [single points: ___ ].\nx measured with: [instrument, its uncertainty ___ ]; run order: [randomized / swept ___ ].",
    reportOutside: "; outside the tested range, so a best case that assumes the line still holds",
    checklistTitle: "Before you trust a fit",
    ck1: "Plotted the data before fitting.",
    ck2: "Chose the model's shape from the physics, not from R².",
    ck3: "Residuals against fitted value: no bend, no fan.",
    ck4: "Residuals in run order: no runs or trend.",
    ck5: "No single point steering the fit, or it's explained.",
    ck6: "Asked whether x is read with noise or tangled with something that drifted (Module 5).",
    ck7: "Reported the residual SD in units, and ranges on the coefficients.",
    ck8: "Used the prediction band for claims about single readings, only inside the tested range.",
    toolsTitle: "The same steps in Excel, MATLAB and Python",
    colTask: "Task",
    rowFit: "Fit a line",
    rowResid: "Residual plots",
    rowRanges: "Coefficient ranges",
    rowBands: "Confidence and prediction bands",
    rowWeighted: "Weighted fit (Module 3)",
    rowRobust: "Robust or HAC errors (Modules 3, 4)",
    rowNonlin: "Nonlinear fit (Modules 2, 4)",
    rowErrX: "Errors in x (Module 5)",
    tByHand: "By hand from the LINEST outputs",
    tScaleRows: "Multiply x, y and a column of 1s by √w, then LINEST with no constant",
    tNotBuiltIn: "Not built in",
    tSolver: "Solver: minimize the sum of squared residuals",
    tTls: "Total least squares via svd",
    tExcelResid: "Fitted column = slope·x + intercept; residual = y − fitted; scatter plot",
    tExcelCiHtml: "<code>=LINEST(y, x, TRUE, TRUE)</code> gives the standard errors; multiply by <code>=T.INV.2T(0.05, n-2)</code>",
    toolsNote: "Function names are the common ones; check your version's documentation.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Two bands, two questions.</b> \"Where's the true line?\" uses the confidence band. \"Where will the next reading land?\" uses the prediction band, which never shrinks below the sensor's noise.",
    take2Html: "<b>Both bands assume the model still holds.</b> Outside the tested range, they're a best case.",
    take3Html: "<b>Derived results need the full covariance.</b> Slope and intercept are correlated; use the delta method or a bootstrap.",
    take4Html: "<b>Report the residual SD in units, ranges on every number, and what you checked.</b> R² alone isn't a result (Module 1).",
    checkTitle: "The series in one line each",
    check1Title: "Modules 1–2",
    check1Body: "Look at the data and the residuals; R² can't tell good from bad.",
    check2Title: "Modules 3–4",
    check2Body: "Uneven scatter and linked errors leave the line alone but break the error bars.",
    check3Title: "Module 5",
    check3Body: "Noise in x and hidden drift bias the line itself, invisibly. Design the experiment to prevent it.",
    footNote: "Simulated data. Trials 1 and 3: y = 1 + 2x, noise SD 2, 15 readings. Trial 2: y = 2(x − c) with c the left edge of the data, noise SD 1, 12 readings.",
    footRead: "Further reading: JCGM 100:2008, Guide to the Expression of Uncertainty in Measurement (the GUM); the NIST/SEMATECH e-Handbook of Statistical Methods."
  },
  es: {
    pageTitle: "Cómo usar y reportar un ajuste · Cómo leer tus ajustes de curvas",
    eyebrow: "Cómo leer tus ajustes de curvas · Módulo 6",
    h1: "Cómo usar y reportar un ajuste",
    lead: "Una vez que pasa las revisiones, el ajuste es una herramienta: para predecir una lectura, estimar una constante o calcular algo a partir de los coeficientes. Cada uso necesita su propio tipo de barra de error.",
    introHtml: "Este módulo cubre las dos bandas que trae todo ajuste, cómo llevar la incertidumbre del ajuste a un número que calculas con él y qué dejar por escrito. Todos los datos se simulan a partir de y = 1 + 2x, con un ruido del sensor de desviación estándar 2, salvo que una prueba diga otra cosa.",
    keyAria: "Leyenda de colores",
    keyTruth: "La verdad",
    keyFit: "El ajuste, y la banda de la recta en sí",
    keyFix: "Un segundo método para comparar",
    keyPts: "Puntos medidos",
    takeLabel: "Llévatelo:",
    takeSlides: "Diapositivas (en inglés)",
    takePy: "Script de Python",
    btnNewSample: "Generar datos nuevos",
    pmFmt: "± {h}",
    yes: "sí",
    no: "no",

    // Trial 1
    t1Num: "Prueba 1 de 3",
    t1Title: "Dos bandas: la recta y la siguiente lectura",
    t1Intro: "Quince lecturas entre x = 0 y x = 10. Mueve el punto donde quieres una respuesta, incluso más allá de los datos.",
    t1XLabel: "Dónde quieres una predicción (x)",
    roYhat: "y ajustada ahí",
    roCi: "Dónde está la recta verdadera (95%)",
    roPi: "Dónde caerá la siguiente lectura (95%)",
    roInside: "¿Dentro del rango probado?",
    t1DataAria: "Datos, recta ajustada, banda de confianza y banda de predicción",
    t1DataCapHtml: "<b>Banda roja: dónde está la recta verdadera. Banda gris: dónde caerá una lectura nueva.</b> Las franjas sombreadas están fuera del rango probado.",
    t1WidthAria: "Semiancho de las dos bandas a lo largo de x",
    t1WidthCapHtml: "<b>Qué tan ancha es cada banda a lo largo de x.</b> Las dos son más angostas en el medio de los datos y se abren hacia afuera.",
    axX: "x",
    axY: "y",
    axHalf: "semiancho de la banda del 95%",
    lblCi: "recta verdadera",
    lblPi: "siguiente lectura",
    lblOutside: "fuera de los datos",
    t1NoteInHtml: "<b>Dentro de los datos, la respuesta depende de la pregunta.</b> La recta verdadera está a ±{ci} de {y}. Una sola lectura nueva caerá a ±{pi}: más ancho, porque lleva el ruido propio del sensor además de la incertidumbre de la recta, y esa parte nunca se achica con más datos.",
    t1NoteOutHtml: "<b>Estás {d} unidades más allá de los datos.</b> Las dos bandas se abrieron (±{ci} para la recta, ±{pi} para una lectura), y esa es la versión <i>optimista</i>: supone que la recta sigue valiendo aquí afuera. Nada en los datos puede confirmarlo. Extrapola solo hasta donde te lo permita la física.",

    // Trial 2
    t2Num: "Prueba 2 de 3",
    t2Title: "Llevar la incertidumbre a un resultado",
    t2Intro: "Muchas veces la respuesta no es un coeficiente sino algo que se calcula con los dos: aquí, la x donde la recta cruza el cero (como la temperatura en la que la salida de un sensor cruza 0 V). La ordenada al origen b0 es el valor del ajuste en x = 0, que puede estar lejos de donde tomaste los datos.",
    t2DLabel: "Qué tan lejos de x = 0 están los datos",
    t2DHelp: "Los datos abarcan 5 unidades a partir de aquí. La recta verdadera cruza el cero en el borde izquierdo de los datos.",
    roCross: "Cruce estimado",
    roTrueCross: "Cruce verdadero",
    roNaive: "Intervalo del 95%, sin la correlación",
    roDelta: "Intervalo del 95%, con la correlación",
    roBoot: "Intervalo del 95%, bootstrap",
    roActual: "Dispersión real en 400 repeticiones",
    t2DataAria: "Datos y recta ajustada prolongada hasta donde cruza el cero, con dos barras de error en el cruce",
    t2DataCapHtml: "<b>El ajuste, prolongado hasta donde cruza el cero.</b> Barra roja: intervalo sin la correlación. Barra azul: con ella.",
    t2HistAria: "Cruces de 400 experimentos repetidos con los dos intervalos marcados",
    t2HistCapHtml: "<b>Cruces en 400 repeticiones del experimento.</b> Un buen intervalo del 95% debería abarcar más o menos el 95% central de este montón.",
    axCross: "cruce estimado (x)",
    axRepeats: "repeticiones",
    lblNaive: "sin la correlación",
    lblDelta: "con la correlación",
    t2NoteHtml: "<b>Ignorar cómo se mueven juntas la pendiente y la ordenada al origen da ±{n}; tenerlo en cuenta da ±{d}.</b> Cuanto más lejos de x = 0 están los datos, peor funciona el primer método. Las repeticiones en realidad se dispersan ±{a}, y un bootstrap con este único conjunto de datos da ±{b}, cerca de eso (varía de una muestra a otra). La ordenada al origen y la pendiente se estiman con los mismos puntos, así que cuando una sale alta, la otra sale baja. Usa la covarianza completa (el <i>método delta</i>) o un bootstrap, nunca los dos errores estándar por separado.",
    t2NoteNearHtml: "<b>Con los datos cerca de x = 0, los dos métodos casi coinciden</b> (±{n} y ±{d}; real ±{a}). Aleja los datos del cero y mira cómo se separan.",

    // Trial 3
    t3Num: "Prueba 3 de 3",
    t3Title: "Qué dejar por escrito",
    t3Intro: "Un texto para el reporte, armado con los datos de la Prueba 1. Cópialo en un reporte de laboratorio y completa las partes que solo tú puedes revisar.",
    t3ReportLabel: "Texto del reporte",
    btnCopy: "Copiar",
    copied: "Copiado",
    copyFail: "Selecciona el texto y cópialo",
    reportTpl: "Ajuste lineal por mínimos cuadrados, y = b0 + b1·x, n = {n} lecturas entre x = {xlo} y {xhi}.\nPendiente b1 = {b1} ± {b1h} (intervalo del 95%); ordenada al origen b0 = {b0} ± {b0h}.\nDesviación estándar de los residuos s = {s} (en unidades de y): una lectura típica queda a esta distancia de la recta.\nPredicción en x = {x0}: {yhat} ± {pih} para una sola lectura nueva (95%){outside}.\nRevisión de residuos: [contra el valor ajustado: ___ ] [en orden de medición: ___ ] [puntos sueltos: ___ ].\nx medida con: [instrumento, su incertidumbre ___ ]; orden de medición: [aleatorio / barrido ___ ].",
    reportOutside: "; fuera del rango probado, así que es el mejor caso y supone que la recta sigue valiendo",
    checklistTitle: "Antes de confiar en un ajuste",
    ck1: "Graficaste los datos antes de ajustar.",
    ck2: "Elegiste la forma del modelo a partir de la física, no del R².",
    ck3: "Residuos contra el valor ajustado: sin curvatura ni abanico.",
    ck4: "Residuos en orden de medición: sin rachas ni tendencia.",
    ck5: "Ningún punto suelto dirige el ajuste, o está explicado.",
    ck6: "Te preguntaste si x se lee con ruido o si está enredada con algo que derivó (Módulo 5).",
    ck7: "Reportaste la desviación estándar de los residuos en unidades, e intervalos para los coeficientes.",
    ck8: "Usaste la banda de predicción para afirmaciones sobre lecturas individuales, solo dentro del rango probado.",
    toolsTitle: "Los mismos pasos en Excel, MATLAB y Python",
    colTask: "Tarea",
    rowFit: "Ajustar una recta",
    rowResid: "Gráficas de residuos",
    rowRanges: "Intervalos de los coeficientes",
    rowBands: "Bandas de confianza y de predicción",
    rowWeighted: "Ajuste ponderado (Módulo 3)",
    rowRobust: "Errores robustos o HAC (Módulos 3 y 4)",
    rowNonlin: "Ajuste no lineal (Módulos 2 y 4)",
    rowErrX: "Errores en x (Módulo 5)",
    tByHand: "A mano, con los resultados de ESTIMACION.LINEAL (LINEST)",
    tScaleRows: "Multiplica por √w la x, la y y una columna de unos, y luego usa ESTIMACION.LINEAL (LINEST) sin constante",
    tNotBuiltIn: "No viene incluido",
    tSolver: "Solver: minimiza la suma de los residuos al cuadrado",
    tTls: "Mínimos cuadrados totales con svd",
    tExcelResid: "Columna ajustada = pendiente·x + ordenada; residuo = y − ajustada; gráfica de dispersión",
    tExcelCiHtml: "<code>=ESTIMACION.LINEAL(y; x; VERDADERO; VERDADERO)</code> (LINEST en Excel en inglés) da los errores estándar; multiplícalos por <code>=INV.T.2C(0,05; n-2)</code> (T.INV.2T en Excel en inglés)",
    toolsNote: "Los nombres de funciones son los más comunes; revisa la documentación de tu versión. La tabla usa los nombres de Excel en inglés; en Excel en español son PENDIENTE (SLOPE), INTERSECCION.EJE (INTERCEPT) y ESTIMACION.LINEAL (LINEST), y los argumentos se separan con \";\".",

    // Takeaways
    takeTitle: "Para recordar",
    take1Html: "<b>Dos bandas, dos preguntas.</b> \"¿Dónde está la recta verdadera?\" usa la banda de confianza. \"¿Dónde caerá la siguiente lectura?\" usa la banda de predicción, que nunca se achica por debajo del ruido del sensor.",
    take2Html: "<b>Las dos bandas suponen que el modelo sigue valiendo.</b> Fuera del rango probado, son el mejor caso.",
    take3Html: "<b>Los resultados derivados necesitan la covarianza completa.</b> La pendiente y la ordenada al origen están correlacionadas; usa el método delta o un bootstrap.",
    take4Html: "<b>Reporta la desviación estándar de los residuos en unidades, un intervalo para cada número y qué revisaste.</b> R² por sí solo no es un resultado (Módulo 1).",
    checkTitle: "La serie, en una línea por tema",
    check1Title: "Módulos 1 y 2",
    check1Body: "Mira los datos y los residuos; R² no distingue lo bueno de lo malo.",
    check2Title: "Módulos 3 y 4",
    check2Body: "La dispersión desigual y los errores ligados no afectan la recta, pero rompen las barras de error.",
    check3Title: "Módulo 5",
    check3Body: "El ruido en x y una deriva oculta sesgan la recta misma, sin que se note. Diseña el experimento para evitarlo.",
    footNote: "Datos simulados. Pruebas 1 y 3: y = 1 + 2x, ruido con desviación estándar 2, 15 lecturas. Prueba 2: y = 2(x − c), con c el borde izquierdo de los datos, ruido con desviación estándar 1, 12 lecturas.",
    footRead: "Lecturas recomendadas: JCGM 100:2008, Guide to the Expression of Uncertainty in Measurement (la GUM); el NIST/SEMATECH e-Handbook of Statistical Methods."
  },
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Guide to the Expression of Uncertainty in Measurement", es: "Guide to the Expression of Uncertainty in Measurement" }, href: "jcgm-100-2008.pdf" },
    { phrase: { en: "NIST/SEMATECH e-Handbook of Statistical Methods", es: "NIST/SEMATECH e-Handbook of Statistical Methods" }, href: "https://www.itl.nist.gov/div898/handbook/index.htm" }
  ]
};
