// strings.js — Using and reporting a fit (Reading Your Fits, Module 6).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js. `es` is filled in during the Spanish pass.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Using and Reporting a Fit · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 6",
    h1: "Using and Reporting a Fit",
    lead: "Once the checks pass, the fit is a tool: for predicting a reading, estimating a constant, or computing something from the coefficients. Each use needs its own kind of error bar.",
    introHtml: "This module covers the two bands every fit comes with, how to carry the fit's uncertainty into a number you compute from it, and what to write down. All data is simulated from y = 1 + 2x with sensor noise SD 2 unless a trial says otherwise.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The fit, and the band for the line itself",
    keyFix: "A second method for comparison",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    btnNewSample: "Draw a new sample",
    pmFmt: "± {h}",
    yes: "yes",
    no: "no",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "Two bands: the line, and the next reading",
    t1Intro: "Fifteen readings over x = 0 to 10. Slide the point where you want an answer, including past the data.",
    t1XLabel: "Where you want a prediction (x)",
    roYhat: "Fitted y there",
    roCi: "Where the true line is (95%)",
    roPi: "Where the next reading will land (95%)",
    roInside: "Inside the tested range?",
    t1DataAria: "Data, fitted line, confidence band and prediction band",
    t1DataCapHtml: "<b>Red band: where the true line is. Grey band: where a new reading will land.</b> The shaded strips are outside the tested range.",
    t1WidthAria: "Half-width of both bands along x",
    t1WidthCapHtml: "<b>How wide each band is along x.</b> Both are narrowest in the middle of the data and flare outward.",
    axX: "x",
    axY: "y",
    axHalf: "half-width of the 95% band",
    lblCi: "true line",
    lblPi: "next reading",
    lblOutside: "outside the data",
    t1NoteInHtml: "<b>Inside the data, the answer depends on the question.</b> The true line is within ±{ci} of {y}. A single new reading will land within ±{pi}: wider, because it carries the sensor's own noise on top of the line's uncertainty, and that part never shrinks with more data.",
    t1NoteOutHtml: "<b>You're {d} units past the data.</b> Both bands have flared (±{ci} for the line, ±{pi} for a reading), and that's the <i>optimistic</i> version: it assumes the straight line still holds out here. Nothing in the data can confirm that. Extrapolate only as far as the physics lets you.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "Carrying the uncertainty into a result",
    t2Intro: "Often the answer isn't a coefficient but something computed from both: here, the x where the line crosses zero (like the temperature where a sensor's output crosses 0 V). The intercept b0 is the fit's value at x = 0, which may be far from where you took data.",
    t2DLabel: "How far the data sit from x = 0",
    t2DHelp: "The data span 5 units starting here. The true line crosses zero at the left edge of the data.",
    roCross: "Estimated crossing",
    roTrueCross: "True crossing",
    roNaive: "95% range, ignoring correlation",
    roDelta: "95% range, with correlation",
    roBoot: "95% range, bootstrap",
    roActual: "Actual spread over 400 repeats",
    t2DataAria: "Data and fitted line extended back to where it crosses zero, with two error bars on the crossing",
    t2DataCapHtml: "<b>The fit, extended back to where it crosses zero.</b> Red bar: range ignoring correlation. Blue bar: range with it.",
    t2HistAria: "Crossings from 400 repeated experiments with both ranges marked",
    t2HistCapHtml: "<b>Crossings from 400 repeats of the experiment.</b> A good 95% range should span about the middle 95% of this pile.",
    axCross: "estimated crossing (x)",
    axRepeats: "repeats",
    lblNaive: "ignoring correlation",
    lblDelta: "with correlation",
    t2NoteHtml: "<b>Ignoring how the slope and intercept move together gives ±{n}; accounting for it gives ±{d}.</b> The farther the data sit from x = 0, the worse the first method gets. The repeats actually spread ±{a}, and a bootstrap from this one dataset gives ±{b}, close to it (it varies from sample to sample). The intercept and slope are estimated from the same points, so when one comes out high the other comes out low. Use the full covariance (the <i>delta method</i>) or a bootstrap, never the two standard errors on their own.",
    t2NoteNearHtml: "<b>With the data near x = 0, the two methods nearly agree</b> (±{n} and ±{d}; actual ±{a}). Slide the data away from zero and watch them part.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "What to write down",
    t3Intro: "A report line built from Trial 1's data. Copy it into a lab report and fill in the parts only you can check.",
    t3ReportLabel: "Report text",
    btnCopy: "Copy",
    copied: "Copied",
    copyFail: "Select the text and copy it",
    reportTpl: "Linear least-squares fit, y = b0 + b1·x, n = {n} readings over x = {xlo} to {xhi}.\nSlope b1 = {b1} ± {b1h} (95% range); intercept b0 = {b0} ± {b0h}.\nResidual SD s = {s} (in y's units): a typical reading sits this far from the line.\nPrediction at x = {x0}: {yhat} ± {pih} for a single new reading (95%){outside}.\nResidual checks: [against fitted value: ___ ] [in run order: ___ ] [single points: ___ ].\nx measured with: [instrument, its uncertainty ___ ]; run order: [randomized / swept ___ ].",
    reportOutside: "; outside the tested range, so a best case that assumes the line still holds",
    checklistTitle: "Before you trust a fit",
    ck1: "Plotted the data before fitting.",
    ck2: "Chose the model's shape from the physics, not from R².",
    ck3: "Residuals against fitted value: no bend, no fan.",
    ck4: "Residuals in run order: no runs or trend.",
    ck5: "No single point steering the fit, or it's explained.",
    ck6: "Asked whether x is read with noise or tangled with something that drifted (Module 5).",
    ck7: "Reported the residual SD in units, and ranges on the coefficients.",
    ck8: "Used the prediction band for claims about single readings, only inside the tested range.",
    toolsTitle: "The same steps in Excel, MATLAB and Python",
    colTask: "Task",
    rowFit: "Fit a line",
    rowResid: "Residual plots",
    rowRanges: "Coefficient ranges",
    rowBands: "Confidence and prediction bands",
    rowWeighted: "Weighted fit (Module 3)",
    rowRobust: "Robust or HAC errors (Modules 3, 4)",
    rowNonlin: "Nonlinear fit (Modules 2, 4)",
    rowErrX: "Errors in x (Module 5)",
    tByHand: "By hand from the LINEST outputs",
    tScaleRows: "Multiply x, y and a column of 1s by √w, then LINEST with no constant",
    tNotBuiltIn: "Not built in",
    tSolver: "Solver: minimize the sum of squared residuals",
    tTls: "Total least squares via svd",
    tExcelResid: "Fitted column = slope·x + intercept; residual = y − fitted; scatter plot",
    tExcelCiHtml: "<code>=LINEST(y, x, TRUE, TRUE)</code> gives the standard errors; multiply by <code>=T.INV.2T(0.05, n-2)</code>",
    toolsNote: "Function names are the common ones; check your version's documentation.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Two bands, two questions.</b> \"Where's the true line?\" uses the confidence band. \"Where will the next reading land?\" uses the prediction band, which never shrinks below the sensor's noise.",
    take2Html: "<b>Both bands assume the model still holds.</b> Outside the tested range, they're a best case.",
    take3Html: "<b>Derived results need the full covariance.</b> Slope and intercept are correlated; use the delta method or a bootstrap.",
    take4Html: "<b>Report the residual SD in units, ranges on every number, and what you checked.</b> R² alone isn't a result (Module 1).",
    checkTitle: "The series in one line each",
    check1Title: "Modules 1–2",
    check1Body: "Look at the data and the residuals; R² can't tell good from bad.",
    check2Title: "Modules 3–4",
    check2Body: "Uneven scatter and linked errors leave the line alone but break the error bars.",
    check3Title: "Module 5",
    check3Body: "Noise in x and hidden drift bias the line itself, invisibly. Design the experiment to prevent it.",
    footNote: "Simulated data. Trials 1 and 3: y = 1 + 2x, noise SD 2, 15 readings. Trial 2: y = 2(x − c) with c the left edge of the data, noise SD 1, 12 readings.",
    footRead: "Further reading: JCGM 100:2008, Guide to the Expression of Uncertainty in Measurement (the GUM); the NIST/SEMATECH e-Handbook of Statistical Methods."
  },
  es: {},
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Guide to the Expression of Uncertainty in Measurement" }, href: "jcgm-100-2008.pdf" },
    { phrase: { en: "NIST/SEMATECH e-Handbook of Statistical Methods" }, href: "https://www.itl.nist.gov/div898/handbook/index.htm" }
  ]
};
