// strings.js — Time-ordered data (Reading Your Fits, Module 4).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Time-Ordered Data · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 4",
    h1: "Time-Ordered Data",
    lead: "A data logger can record a thousand samples a minute. That doesn't give you a thousand independent pieces of evidence, and your error bars don't know it.",
    introHtml: "When each reading is tied to the one before it (filtering, slow dynamics, drift), the errors are <b>autocorrelated</b>: the leftovers come in runs instead of scattering independently. The fitted line survives. Its error bars, and anything you fit after a log transform, may not. All data here is simulated.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The usual method",
    keyFix: "The better method",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    btnNewSample: "Draw a new sample",
    pctOf: "{p}%",
    unitMin: "{v} min",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "Sampling faster than the noise changes",
    t1Intro: "A slow drift fitted with a line, 100 samples. The slider sets how strongly each sample's error carries over into the next one.",
    t1RhoLabel: "Carry-over between samples",
    t1RhoHelp: "0 = every sample's error is fresh. 0.9 = each error is 90% the previous one plus a little new noise. Fast logging through a filter lands near the top.",
    roLag1: "Lag-1 autocorrelation of residuals",
    roDw: "Durbin–Watson (2 = none)",
    roNeff: "Samples' worth of evidence, roughly",
    neffFmt: "{e} of {n}",
    roCover: "Slope range catches the truth",
    t1ResidAria: "Residuals in time order",
    t1ResidCapHtml: "<b>Residuals in time order.</b> Runs of the same sign mean the errors are linked.",
    t1AcfAria: "Autocorrelation of the residuals at lags 1 to 15",
    t1AcfCapHtml: "<b>Autocorrelation at lags 1–15:</b> how alike residuals are 1, 2, … samples apart. Dashed lines: the band chance alone stays inside. Red bars fall outside it: linked errors.",
    axSample: "sample number (time order)",
    axResidual: "residual",
    axLag: "lag (samples)",
    axAcf: "autocorrelation",
    t1NoteLowHtml: "<b>Little carry-over:</b> the residuals scatter independently, Durbin–Watson is near 2, and the slope's 95% range catches the truth about 95% of the time ({c}%).",
    t1NoteMildHtml: "<b>Slightly linked errors.</b> With carry-over {rho}, the slope's 95% range catches the truth {c}% of the time, a little under 95%. Easy to miss in the residual plot, and it gets worse fast as the carry-over rises.",
    t1NoteHighHtml: "<b>The residuals come in long runs, and the error bars are fooled.</b> The software treats all {n} samples as independent, but they carry roughly {e} samples' worth of evidence. So the slope's 95% range is too narrow and catches the truth only {c}% of the time over 400 repeats. Plotting residuals in time order shows it at a glance.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "The cooling-curve log trap",
    t2Intro: "A thermocouple cools from 80 °C toward a 22 °C room with time constant 4 min. The textbook shortcut: plot ln(T − T∞) against time and read −1/τ as the slope. Compare it with fitting the exponential directly.",
    t2MethodLabel: "Method",
    mLog: "Log, then line",
    mDirect: "Fit the exponential",
    t2NoiseLabel: "Sensor noise",
    t2RoomLabel: "Error in the room temperature you assumed",
    t2RoomHelp: "The log method needs T∞ exactly. The direct fit estimates it.",
    unitC: "{v} °C",
    unitCSigned: "{s}{v} °C",
    roTauLog: "τ from the log method",
    roTauDir: "τ from the direct fit",
    roDropped: "Points the log method had to drop",
    droppedFmt: "{d} of {n}",
    roAvgLog: "Average τ over 200 runs, log",
    roAvgDir: "Average τ over 200 runs, direct",
    roTrueTau: "True τ",
    t2LogAria: "Natural log of temperature minus room temperature against time",
    t2LogCapHtml: "<b>ln(T − T∞) against time.</b> Should be a straight line. Hollow points were dropped (T − T∞ ≤ 0).",
    t2CurveAria: "Temperature against time with the fitted curve",
    t2CurveCapHtml: "<b>The cooling curve and the chosen fit.</b>",
    axTime: "time (min)",
    axLn: "ln(T − T∞)",
    axTemp: "temperature (°C)",
    t2NoteLogHtml: "<b>The log method gets τ = {tau} min; over 200 recordings it averages {avg} against a true 4.0.</b> Three things go wrong. The log stretches the tail's noise (0.5 °C is tiny at 60 °C above room, huge at 0.5 °C above it), so the late points scatter wildly. Points that dip below T∞ can't be logged and get dropped, which biases what's left. And any error in T∞ bends the late tail. Switch to Fit the exponential.",
    t2NoteDirHtml: "<b>The direct fit gets τ = {tau} min and averages {avg} over 200 recordings.</b> It estimates the room temperature too, doesn't drop anything, and treats every reading's noise the same way the sensor does. The log method on the same data: {tlog} min, average {alog}.",
    t2NoteCleanHtml: "<b>With no noise and the right T∞, both methods agree.</b> The trouble starts with real sensors: add noise or a room-temperature error.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "Every sample, or every run?",
    t3Intro: "You log a steady reading for 60 samples, reset the rig, and repeat for 5 runs. Each run settles a little differently. What's the steady value, and how sure are you?",
    t3CountLabel: "Count as one piece of evidence",
    cSample: "Each sample (300)",
    cRun: "Each run (5)",
    t3RunLabel: "Run-to-run variation (SD)",
    t3RunHelp: "How much each run's steady value differs from the long-run value.",
    t3RhoLabel: "Carry-over between samples",
    roEst: "Estimated steady value (truth 50)",
    roRange: "95% range",
    rangeFmt: "{m} ± {h}",
    roCovSample: "Range catches 50, counting samples",
    roCovRun: "Range catches 50, counting runs",
    t3DataAria: "Samples from five runs with each run's mean",
    t3DataCapHtml: "<b>Five runs of 60 samples.</b> Dark ticks: each run's mean.",
    t3CiAria: "95% ranges from 20 repeated experiments",
    t3CiCapHtml: "<b>The 95% range from 20 repeats of the whole experiment.</b> Blue ranges catch the true value (dashed line); red ones miss it.",
    axRepeat: "repeat",
    axValue: "steady value",
    t3NoteSampleHtml: "<b>Counting every sample, the range is ±{h}, and it catches the true value only {c}% of the time.</b> The 60 samples in a run share that run's offset and each other's carry-over, so they aren't 300 independent readings. Switch to Each run.",
    t3NoteSampleRhoHtml: "<b>Counting every sample, the range is ±{h}, and it catches the true value only {c}% of the time.</b> Each sample carries over part of the previous one's error, so the 300 samples hold far fewer independent readings. Switch to Each run.",
    t3NoteRunHtml: "<b>Counting runs, the range is ±{h}: wider, and honest.</b> It catches the true value {c}% of the time (counting samples: {cs}%). Five runs are five pieces of evidence about the run-to-run spread. To shrink the range, do more runs, not more samples per run.",
    t3NoteSameHtml: "<b>With no run-to-run variation and no carry-over, the samples really are independent,</b> and both ways of counting give honest ranges ({cs}% and {c}%). Turn either slider up.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Always plot residuals in the order you took them.</b> Runs of the same sign mean the errors are linked, and the error bars are too narrow.",
    take2Html: "<b>Fix the model first.</b> Autocorrelated residuals often mean missing dynamics: a drift term, a second time constant, a warm-up. Then use Newey–West (HAC) standard errors for what's left.",
    take3Html: "<b>Don't log-linearize a decay to fit it.</b> Fit the exponential directly (curve_fit, fitnlm, Solver). The same goes for log decrement on noisy ringdowns: use many cycles or fit the damped sine.",
    take4Html: "<b>Count runs, not samples,</b> when runs differ. More samples per run don't shrink run-to-run uncertainty; more runs do.",
    checkTitle: "Checks in your software",
    check1Title: "Excel",
    check1Body: "Plot residuals against row number. Lag-1 correlation: =CORREL(D3:D101, D2:D100).",
    check2Title: "MATLAB",
    check2Body: "dwtest(mdl) for Durbin–Watson, autocorr(res) for the lag plot, fitnlm for the exponential.",
    check3Title: "Python",
    check3Body: "statsmodels durbin_watson, plot_acf, fit(cov_type='HAC', cov_kwds={'maxlags': L}); scipy curve_fit for the exponential.",
    footNote: "Simulated data. Trial 1: y = 1 + 0.2t + AR(1) noise, SD 1. Trial 2: T = 22 + 58·e^(−t/4) + noise, every 15 s for 20 min. Trial 3: steady value 50, run offsets and AR(1) noise with SD 1.",
    footRead: "Further reading: Durbin and Watson, \"Testing for Serial Correlation in Least Squares Regression\", part I (1950) and part II (1951); Newey and West (1987), \"A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix\"."
  },
  es: {
    pageTitle: "Datos ordenados en el tiempo · Cómo leer tus ajustes de curvas",
    eyebrow: "Cómo leer tus ajustes de curvas · Módulo 4",
    h1: "Datos ordenados en el tiempo",
    lead: "Un registrador de datos puede guardar mil muestras por minuto. Eso no te da mil pruebas independientes, y tus barras de error no lo saben.",
    introHtml: "Cuando cada lectura está atada a la anterior (por un filtro, una dinámica lenta o una deriva), los errores están <b>autocorrelacionados</b>: los residuos vienen en rachas en vez de dispersarse de forma independiente. La recta ajustada aguanta. Sus barras de error, y cualquier cosa que ajustes después de sacar un logaritmo, tal vez no. Todos los datos de esta página son simulados.",
    keyAria: "Leyenda de colores",
    keyTruth: "La verdad",
    keyFit: "El método de siempre",
    keyFix: "El mejor método",
    keyPts: "Puntos medidos",
    takeLabel: "Llévatelo:",
    takeSlides: "Diapositivas (en inglés)",
    takePy: "Script de Python",
    btnNewSample: "Generar datos nuevos",
    pctOf: "{p}%",
    unitMin: "{v} min",

    // Trial 1
    t1Num: "Prueba 1 de 3",
    t1Title: "Muestrear más rápido de lo que cambia el ruido",
    t1Intro: "Una deriva lenta ajustada con una recta, 100 muestras. El deslizador fija cuánto del error de cada muestra se arrastra a la siguiente.",
    t1RhoLabel: "Arrastre entre muestras",
    t1RhoHelp: "0 = el error de cada muestra es nuevo. 0,9 = cada error es el 90% del anterior más un poco de ruido nuevo. Registrar rápido a través de un filtro te deja cerca del máximo.",
    roLag1: "Autocorrelación de los residuos con retardo 1",
    roDw: "Durbin–Watson (2 = ninguna)",
    roNeff: "Muestras efectivas (aprox.)",
    neffFmt: "{e}\u00A0de\u00A0{n}",
    roCover: "El intervalo de la pendiente contiene la verdad",
    t1ResidAria: "Residuos en orden temporal",
    t1ResidCapHtml: "<b>Residuos en orden temporal.</b> Las rachas del mismo signo indican que los errores están ligados.",
    t1AcfAria: "Autocorrelación de los residuos con retardos de 1 a 15",
    t1AcfCapHtml: "<b>Autocorrelación con retardos de 1 a 15:</b> qué tan parecidos son los residuos separados por 1, 2, … muestras. Líneas discontinuas: la banda dentro de la que se queda el puro azar. Las barras rojas caen fuera de ella: errores ligados.",
    axSample: "número de muestra (orden en el tiempo)",
    axResidual: "residuo",
    axLag: "retardo (muestras)",
    axAcf: "autocorrelación",
    t1NoteLowHtml: "<b>Poco arrastre:</b> los residuos se dispersan de forma independiente, Durbin–Watson está cerca de 2 y el intervalo del 95% de la pendiente contiene la verdad alrededor del 95% de las veces ({c}%).",
    t1NoteMildHtml: "<b>Errores un poco ligados.</b> Con un arrastre de {rho}, el intervalo del 95% de la pendiente contiene la verdad el {c}% de las veces, un poco menos del 95%. Es fácil no verlo en la gráfica de residuos, y empeora rápido a medida que sube el arrastre.",
    t1NoteHighHtml: "<b>Los residuos vienen en rachas largas, y las barras de error se engañan.</b> El software trata las {n} muestras como independientes, pero traen la evidencia de unas {e} muestras. Por eso el intervalo del 95% de la pendiente es demasiado angosto y contiene la verdad solo el {c}% de las veces en 400 repeticiones. Graficar los residuos en orden temporal lo muestra de un vistazo.",

    // Trial 2
    t2Num: "Prueba 2 de 3",
    t2Title: "La trampa del logaritmo en la curva de enfriamiento",
    t2Intro: "Un termopar se enfría desde 80 °C hacia un cuarto a 22 °C, con una constante de tiempo de 4 min. El atajo de los libros: graficar ln(T − T∞) contra el tiempo y leer −1/τ como la pendiente. Compáralo con ajustar la exponencial directamente.",
    t2MethodLabel: "Método",
    mLog: "Log y luego recta",
    mDirect: "Ajustar la exponencial",
    t2NoiseLabel: "Ruido del sensor",
    t2RoomLabel: "Error en la temperatura ambiente que supusiste",
    t2RoomHelp: "El método del logaritmo necesita T∞ exacta. El ajuste directo la estima.",
    unitC: "{v} °C",
    unitCSigned: "{s}{v} °C",
    roTauLog: "τ con el método del logaritmo",
    roTauDir: "τ con el ajuste directo",
    roDropped: "Puntos que el método del logaritmo tuvo que descartar",
    droppedFmt: "{d}\u00A0de\u00A0{n}",
    roAvgLog: "τ promedio en 200 registros, logaritmo",
    roAvgDir: "τ promedio en 200 registros, directo",
    roTrueTau: "τ verdadera",
    t2LogAria: "Logaritmo natural de la temperatura menos la temperatura ambiente, contra el tiempo",
    t2LogCapHtml: "<b>ln(T − T∞) contra el tiempo.</b> Debería ser una recta. Los puntos huecos se descartaron (T − T∞ ≤ 0).",
    t2CurveAria: "Temperatura contra tiempo, con la curva ajustada",
    t2CurveCapHtml: "<b>La curva de enfriamiento y el ajuste elegido.</b>",
    axTime: "tiempo (min)",
    axLn: "ln(T − T∞)",
    axTemp: "temperatura (°C)",
    t2NoteLogHtml: "<b>El método del logaritmo da τ = {tau} min; en 200 registros promedia {avg}, frente a un valor verdadero de 4,0.</b> Fallan tres cosas. El logaritmo estira el ruido de la cola (0,5 °C es muy poco a 60 °C por encima del ambiente y muchísimo a 0,5 °C por encima), así que los últimos puntos se dispersan muchísimo. Los puntos que bajan de T∞ no tienen logaritmo y se descartan, lo que sesga lo que queda. Y cualquier error en T∞ dobla el final de la cola. Cambia a Ajustar la exponencial.",
    t2NoteDirHtml: "<b>El ajuste directo da τ = {tau} min y promedia {avg} en 200 registros.</b> También estima la temperatura ambiente, no descarta nada y trata el ruido de cada lectura igual que el sensor. El método del logaritmo con los mismos datos: {tlog} min, promedio {alog}.",
    t2NoteCleanHtml: "<b>Sin ruido y con la T∞ correcta, los dos métodos coinciden.</b> Los problemas empiezan con sensores reales: agrega ruido o un error en la temperatura ambiente.",

    // Trial 3
    t3Num: "Prueba 3 de 3",
    t3Title: "¿Cada muestra o cada corrida?",
    t3Intro: "Registras una lectura estable durante 60 muestras, reinicias el montaje y repites hasta tener 5 corridas. Cada corrida se estabiliza un poco distinto. ¿Cuál es el valor estable y qué tan seguro estás?",
    t3CountLabel: "Contar como una prueba independiente",
    cSample: "Cada muestra (300)",
    cRun: "Cada corrida (5)",
    t3RunLabel: "Variación entre corridas (desv. est.)",
    t3RunHelp: "Cuánto se aleja el valor estable de cada corrida del valor a largo plazo.",
    t3RhoLabel: "Arrastre entre muestras",
    roEst: "Valor estable estimado (verdad: 50)",
    roRange: "Intervalo del 95%",
    rangeFmt: "{m} ± {h}",
    roCovSample: "El intervalo contiene 50, contando muestras",
    roCovRun: "El intervalo contiene 50, contando corridas",
    t3DataAria: "Muestras de cinco corridas con el promedio de cada corrida",
    t3DataCapHtml: "<b>Cinco corridas de 60 muestras.</b> Marcas oscuras: el promedio de cada corrida.",
    t3CiAria: "Intervalos del 95% de 20 experimentos repetidos",
    t3CiCapHtml: "<b>El intervalo del 95% en 20 repeticiones del experimento completo.</b> Los intervalos azules contienen el valor verdadero (línea discontinua); los rojos no.",
    axRepeat: "repetición",
    axValue: "valor estable",
    t3NoteSampleHtml: "<b>Contando cada muestra, el intervalo es ±{h}, y contiene el valor verdadero solo el {c}% de las veces.</b> Las 60 muestras de una corrida comparten el desfase de esa corrida y el arrastre entre ellas, así que no son 300 lecturas independientes. Cambia a Cada corrida.",
    t3NoteSampleRhoHtml: "<b>Contando cada muestra, el intervalo es ±{h}, y contiene el valor verdadero solo el {c}% de las veces.</b> Cada muestra arrastra parte del error de la anterior, así que las 300 muestras equivalen a muchas menos lecturas independientes. Cambia a Cada corrida.",
    t3NoteRunHtml: "<b>Contando corridas, el intervalo es ±{h}: más ancho, y honesto.</b> Contiene el valor verdadero el {c}% de las veces (contando muestras: {cs}%). Cinco corridas son cinco pruebas de cuánto varía una corrida respecto de otra. Para achicar el intervalo, haz más corridas, no más muestras por corrida.",
    t3NoteSameHtml: "<b>Sin variación entre corridas y sin arrastre, las muestras sí son independientes,</b> y las dos formas de contar dan intervalos honestos ({cs}% y {c}%). Sube cualquiera de los dos deslizadores.",

    // Takeaways
    takeTitle: "Para recordar",
    take1Html: "<b>Grafica siempre los residuos en el orden en que los tomaste.</b> Las rachas del mismo signo indican que los errores están ligados y que las barras de error son demasiado angostas.",
    take2Html: "<b>Primero corrige el modelo.</b> Los residuos autocorrelacionados muchas veces indican que falta dinámica: un término de deriva, una segunda constante de tiempo, un calentamiento inicial. Después usa errores estándar de Newey–West (HAC) para lo que quede.",
    take3Html: "<b>No linealices un decaimiento con logaritmos para ajustarlo.</b> Ajusta la exponencial directamente (curve_fit, fitnlm, Solver). Lo mismo vale para el decremento logarítmico en oscilaciones amortiguadas con ruido: usa muchos ciclos o ajusta la senoide amortiguada.",
    take4Html: "<b>Cuenta corridas, no muestras,</b> cuando las corridas difieren. Más muestras por corrida no reducen la incertidumbre entre corridas; más corridas sí.",
    checkTitle: "Revisiones en tu software",
    check1Title: "Excel",
    check1Body: "Grafica los residuos contra el número de fila. Correlación con retardo 1: =COEF.DE.CORREL(D3:D101; D2:D100) (CORREL en Excel en inglés).",
    check2Title: "MATLAB",
    check2Body: "dwtest(mdl) para Durbin–Watson, autocorr(res) para la gráfica de retardos, fitnlm para la exponencial.",
    check3Title: "Python",
    check3Body: "statsmodels durbin_watson, plot_acf, fit(cov_type='HAC', cov_kwds={'maxlags': L}); scipy curve_fit para la exponencial.",
    footNote: "Datos simulados. Prueba 1: y = 1 + 0,2t + ruido AR(1), desv. est. 1. Prueba 2: T = 22 + 58·e^(−t/4) + ruido, cada 15 s durante 20 min. Prueba 3: valor estable 50, desfases por corrida y ruido AR(1) con desv. est. 1.",
    footRead: "Lecturas recomendadas: Durbin y Watson, \"Testing for Serial Correlation in Least Squares Regression\", parte I (1950) y parte II (1951); Newey y West (1987), \"A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix\"."
  },
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Durbin–Watson", es: "Durbin–Watson" }, href: "durbin-watson-1950.pdf" },
    { phrase: { en: "Newey–West", es: "Newey–West" }, href: "newey-west-1987.pdf" },
    { phrase: { en: "part I (1950)", es: "parte I (1950)" }, href: "durbin-watson-1950.pdf" },
    { phrase: { en: "part II (1951)", es: "parte II (1951)" }, href: "durbin-watson-1951.pdf" },
    { phrase: { en: "\"A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix\"", es: "\"A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix\"" }, href: "newey-west-1987.pdf" }
  ]
};
