// strings.js — Time-ordered data (Reading Your Fits, Module 4).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js. `es` is filled in during the Spanish pass.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Time-Ordered Data · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 4",
    h1: "Time-Ordered Data",
    lead: "A data logger can record a thousand samples a minute. That doesn't give you a thousand independent pieces of evidence, and your error bars don't know it.",
    introHtml: "When each reading is tied to the one before it (filtering, slow dynamics, drift), the errors are <b>autocorrelated</b>: the leftovers come in runs instead of scattering independently. The fitted line survives. Its error bars, and anything you fit after a log transform, may not. All data here is simulated.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The usual method",
    keyFix: "The better method",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    btnNewSample: "Draw a new sample",
    pctOf: "{p}%",
    unitMin: "{v} min",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "Sampling faster than the noise changes",
    t1Intro: "A slow drift fitted with a line, 100 samples. The slider sets how strongly each sample's error carries over into the next one.",
    t1RhoLabel: "Carry-over between samples",
    t1RhoHelp: "0 = every sample's error is fresh. 0.9 = each error is 90% the previous one plus a little new noise. Fast logging through a filter lands near the top.",
    roLag1: "Lag-1 autocorrelation of residuals",
    roDw: "Durbin–Watson (2 = none)",
    roNeff: "Samples' worth of evidence, roughly",
    neffFmt: "{e} of {n}",
    roCover: "Slope range catches the truth",
    t1ResidAria: "Residuals in time order",
    t1ResidCapHtml: "<b>Residuals in time order.</b> Runs of the same sign mean the errors are linked.",
    t1AcfAria: "Autocorrelation of the residuals at lags 1 to 15",
    t1AcfCapHtml: "<b>Autocorrelation at lags 1–15:</b> how alike residuals are 1, 2, … samples apart. Dashed lines: the band chance alone stays inside. Red bars fall outside it: linked errors.",
    axSample: "sample number (time order)",
    axResidual: "residual",
    axLag: "lag (samples)",
    axAcf: "autocorrelation",
    t1NoteLowHtml: "<b>Little carry-over:</b> the residuals scatter independently, Durbin–Watson is near 2, and the slope's 95% range catches the truth about 95% of the time ({c}%).",
    t1NoteMildHtml: "<b>Slightly linked errors.</b> With carry-over {rho}, the slope's 95% range catches the truth {c}% of the time, a little under 95%. Easy to miss in the residual plot, and it gets worse fast as the carry-over rises.",
    t1NoteHighHtml: "<b>The residuals come in long runs, and the error bars are fooled.</b> The software treats all {n} samples as independent, but they carry roughly {e} samples' worth of evidence. So the slope's 95% range is too narrow and catches the truth only {c}% of the time over 400 repeats. Plotting residuals in time order shows it at a glance.",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "The cooling-curve log trap",
    t2Intro: "A thermocouple cools from 80 °C toward a 22 °C room with time constant 4 min. The textbook shortcut: plot ln(T − T∞) against time and read −1/τ as the slope. Compare it with fitting the exponential directly.",
    t2MethodLabel: "Method",
    mLog: "Log, then line",
    mDirect: "Fit the exponential",
    t2NoiseLabel: "Sensor noise",
    t2RoomLabel: "Error in the room temperature you assumed",
    t2RoomHelp: "The log method needs T∞ exactly. The direct fit estimates it.",
    unitC: "{v} °C",
    unitCSigned: "{s}{v} °C",
    roTauLog: "τ from the log method",
    roTauDir: "τ from the direct fit",
    roDropped: "Points the log method had to drop",
    droppedFmt: "{d} of {n}",
    roAvgLog: "Average τ over 200 runs, log",
    roAvgDir: "Average τ over 200 runs, direct",
    roTrueTau: "True τ",
    t2LogAria: "Natural log of temperature minus room temperature against time",
    t2LogCapHtml: "<b>ln(T − T∞) against time.</b> Should be a straight line. Hollow points were dropped (T − T∞ ≤ 0).",
    t2CurveAria: "Temperature against time with the fitted curve",
    t2CurveCapHtml: "<b>The cooling curve and the chosen fit.</b>",
    axTime: "time (min)",
    axLn: "ln(T − T∞)",
    axTemp: "temperature (°C)",
    t2NoteLogHtml: "<b>The log method gets τ = {tau} min; over 200 recordings it averages {avg} against a true 4.0.</b> Three things go wrong. The log stretches the tail's noise (0.5 °C is tiny at 60 °C above room, huge at 0.5 °C above it), so the late points scatter wildly. Points that dip below T∞ can't be logged and get dropped, which biases what's left. And any error in T∞ bends the late tail. Switch to Fit the exponential.",
    t2NoteDirHtml: "<b>The direct fit gets τ = {tau} min and averages {avg} over 200 recordings.</b> It estimates the room temperature too, doesn't drop anything, and treats every reading's noise the same way the sensor does. The log method on the same data: {tlog} min, average {alog}.",
    t2NoteCleanHtml: "<b>With no noise and the right T∞, both methods agree.</b> The trouble starts with real sensors: add noise or a room-temperature error.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "Every sample, or every run?",
    t3Intro: "You log a steady reading for 60 samples, reset the rig, and repeat for 5 runs. Each run settles a little differently. What's the steady value, and how sure are you?",
    t3CountLabel: "Count as one piece of evidence",
    cSample: "Each sample (300)",
    cRun: "Each run (5)",
    t3RunLabel: "Run-to-run variation (SD)",
    t3RunHelp: "How much each run's steady value differs from the long-run value.",
    t3RhoLabel: "Carry-over between samples",
    roEst: "Estimated steady value (truth 50)",
    roRange: "95% range",
    rangeFmt: "{m} ± {h}",
    roCovSample: "Range catches 50, counting samples",
    roCovRun: "Range catches 50, counting runs",
    t3DataAria: "Samples from five runs with each run's mean",
    t3DataCapHtml: "<b>Five runs of 60 samples.</b> Dark ticks: each run's mean.",
    t3CiAria: "95% ranges from 20 repeated experiments",
    t3CiCapHtml: "<b>The 95% range from 20 repeats of the whole experiment.</b> Blue ranges catch the true value (dashed line); red ones miss it.",
    axRepeat: "repeat",
    axValue: "steady value",
    t3NoteSampleHtml: "<b>Counting every sample, the range is ±{h}, and it catches the true value only {c}% of the time.</b> The 60 samples in a run share that run's offset and each other's carry-over, so they aren't 300 independent readings. Switch to Each run.",
    t3NoteSampleRhoHtml: "<b>Counting every sample, the range is ±{h}, and it catches the true value only {c}% of the time.</b> Each sample carries over part of the previous one's error, so the 300 samples hold far fewer independent readings. Switch to Each run.",
    t3NoteRunHtml: "<b>Counting runs, the range is ±{h}: wider, and honest.</b> It catches the true value {c}% of the time (counting samples: {cs}%). Five runs are five pieces of evidence about the run-to-run spread. To shrink the range, do more runs, not more samples per run.",
    t3NoteSameHtml: "<b>With no run-to-run variation and no carry-over, the samples really are independent,</b> and both ways of counting give honest ranges ({cs}% and {c}%). Turn either slider up.",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Always plot residuals in the order you took them.</b> Runs of the same sign mean the errors are linked, and the error bars are too narrow.",
    take2Html: "<b>Fix the model first.</b> Autocorrelated residuals often mean missing dynamics: a drift term, a second time constant, a warm-up. Then use Newey–West (HAC) standard errors for what's left.",
    take3Html: "<b>Don't log-linearize a decay to fit it.</b> Fit the exponential directly (curve_fit, fitnlm, Solver). The same goes for log decrement on noisy ringdowns: use many cycles or fit the damped sine.",
    take4Html: "<b>Count runs, not samples,</b> when runs differ. More samples per run don't shrink run-to-run uncertainty; more runs do.",
    checkTitle: "Checks in your software",
    check1Title: "Excel",
    check1Body: "Plot residuals against row number. Lag-1 correlation: =CORREL(D3:D101, D2:D100).",
    check2Title: "MATLAB",
    check2Body: "dwtest(mdl) for Durbin–Watson, autocorr(res) for the lag plot, fitnlm for the exponential.",
    check3Title: "Python",
    check3Body: "statsmodels durbin_watson, plot_acf, fit(cov_type='HAC', cov_kwds={'maxlags': L}); scipy curve_fit for the exponential.",
    footNote: "Simulated data. Trial 1: y = 1 + 0.2t + AR(1) noise, SD 1. Trial 2: T = 22 + 58·e^(−t/4) + noise, every 15 s for 20 min. Trial 3: steady value 50, run offsets and AR(1) noise with SD 1.",
    footRead: "Further reading: Durbin and Watson, \"Testing for Serial Correlation in Least Squares Regression\", part I (1950) and part II (1951); Newey and West (1987), \"A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix\"."
  },
  es: {},
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Durbin–Watson" }, href: "durbin-watson-1950.pdf" },
    { phrase: { en: "Newey–West" }, href: "newey-west-1987.pdf" },
    { phrase: { en: "part I (1950)" }, href: "durbin-watson-1950.pdf" },
    { phrase: { en: "part II (1951)" }, href: "durbin-watson-1951.pdf" },
    { phrase: { en: "\"A Simple, Positive Semi-Definite, Heteroskedasticity and Autocorrelation Consistent Covariance Matrix\"" }, href: "newey-west-1987.pdf" }
  ]
};
