// strings.js — The Invisible Bias (Reading Your Fits, Module 5).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "The Invisible Bias · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 5",
    h1: "The Invisible Bias",
    lead: "Most fitting problems leave fingerprints in the residual plot. This one doesn't. The fitted line comes out wrong, the leftovers look perfectly healthy, and taking more data makes you more confident in the wrong answer.",
    introHtml: "Think of x as something you read off an instrument (a thermocouple temperature, a displacement sensor, a measured voltage) and y as the response you record. All data here is simulated, so we know the true slope: <b>2.00</b>.",
    introSetpointHtml: "<b>Reading, not setting.</b> If you set x on a dial and write down the setting, the true value wanders around your setting instead. That is a different kind of error, and it does not bias the slope. This module is about x values you <i>read</i>.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "What an ordinary least-squares fit reports",
    keyFix: "A corrected estimate",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    takePlay: "Play with the code",
    takeColab: "Open in Colab",

    // Trial 1
    t1Num: "Trial 1 of 4",
    t1Title: "Noise in y versus noise in x",
    t1Intro: "Both sliders add random error to a sensor. Only one of them tilts the line.",
    quizPromptHtml: "<b>Predict first.</b> If the sensor that reads x gets noisier, the fitted slope will…",
    quizAria: "Your prediction",
    quizSteeper: "get steeper",
    quizFlatter: "get flatter",
    quizSame: "stay the same, just messier",
    quizRightHtml: "<b>Right: flatter.</b> ",
    quizWrongHtml: "<b>It gets flatter.</b> ",
    quizExplain: "Noise in x spreads the points sideways, which makes the cloud look less steep than it is. Try it: push the x slider up and watch the red line tip toward horizontal, then push the y slider and watch it stay put on average.",
    t1SyLabel: "Noise in y readings",
    t1SyHelp: "Standard deviation of the y sensor's error.",
    t1SxLabel: "Noise in x readings",
    t1SxHelp: "Standard deviation of the x sensor's error. For comparison, the true x values (spread evenly over 0 to 10) have a standard deviation of about 2.9.",
    btnNewSample: "Draw a new sample",
    roTrue: "True slope",
    roFitted: "Fitted slope",
    roOff: "Off by",
    offSmall: "under 2%",
    offFlat: "{p}% too flat",
    offSteep: "{p}% too steep",
    t1ScatterAria: "Measured y versus measured x with the true line and the fitted line",
    t1ScatterCapHtml: "<b>The data and the fit.</b> 50 readings.",
    t1ResidAria: "Residuals versus fitted values",
    t1ResidCapHtml: "<b>Residual plot.</b> Leftover error after the fit, against the fitted value.",
    axMeasuredX: "measured x",
    axMeasuredY: "measured y",
    axFittedY: "fitted y",
    axResidual: "residual",
    t1NoteExactHtml: "<b>With x read accurately, the red fit sits on the truth</b> whatever you do to the y noise. More y noise only fattens the cloud and widens the residual band.",
    t1NoteNoisyHtml: "<b>With x noise at {sx}, an ordinary fit is pulled to about {pct}% of the true slope on average.</b> Now look at the residual plot: a flat, even band around zero, exactly what a healthy fit looks like. Nothing in it warns you.",

    // Trial 2
    t2Num: "Trial 2 of 4",
    t2Title: "Will more data fix it?",
    t2Intro: "Here the same experiment is repeated 400 times. Each bar counts how many repeats got a given slope. The software's 95% error bars should contain the true slope in 95% of repeats.",
    t2SxLabel: "Noise in x readings",
    t2NLabel: "Points per experiment",
    t2Btn: "Repeat all 400 again",
    roAvg: "Average fitted slope",
    roMiddle: "Middle 95% of fits",
    roCaught: "Error bars that caught 2.00",
    rangeFmt: "{lo} to {hi}",
    coverFmt: "{p}% (should be 95%)",
    t2HistAria: "Histogram of fitted slopes from 400 repeated experiments",
    t2HistCapHtml: "<b>Fitted slopes from 400 repeats.</b> Dashed line is the truth; red line is the average fit.",
    axFittedSlope: "fitted slope",
    axRepeats: "number of repeats",
    lblTruth: "truth {v}",
    lblAvg: "average fit {v}",
    t2NoteExactHtml: "<b>No x noise: the repeats center on 2.00,</b> and adding points just narrows the pile around the truth. The error bars catch it about 95% of the time, as promised.",
    t2NoteNoisyHtml: "<b>Click through 10, 100, 1000 points.</b> The pile gets narrower but stays centered near {mean}, not 2.00. ",
    t2NoteLowCoverHtml: "At {n} points the software's 95% error bars catch the true slope in only {cover}% of repeats. More data makes you more certain of the wrong answer.",
    t2NoteOkCoverHtml: "At {n} points the error bars still catch 2.00 in {cover}% of repeats, because the scatter is still wide next to the bias. Pick more points and watch that number fall.",

    // Trial 3
    t3Num: "Trial 3 of 4",
    t3Title: "Something you didn't measure",
    t3Intro: "During the session, something drifts upward: the room warms, a battery sags, a bearing heats up. It nudges every y reading a little more as time goes on. You never measured it.",
    t3DLabel: "Drift over the session",
    t3DHelp: "How much the drift has added to y by the last run.",
    t3OrderLabel: "Order of the runs",
    t3Sweep: "Low to high x",
    t3Random: "Randomized",
    t3ScatterAria: "y versus x, points shaded by when they were taken",
    t3ScatterCapHtml: "<b>The data and the fit.</b> Solid points were taken later; faint ones earlier.",
    t3ResidAria: "Residuals versus run order",
    t3ResidCapHtml: "<b>Residuals in run order.</b> The check for anything that changes with time.",
    axXSetting: "x setting",
    axRunNumber: "run number (time order)",
    t3NoteNoneHtml: "<b>No drift, no problem.</b> Turn the drift up and compare the two run orders.",
    t3NoteSweepHtml: "<b>Sweeping x from low to high ties the drift to x.</b> The fit can't tell them apart, so the drift is folded into the slope. The run-order residuals look like plain noise because the drift was absorbed along with x. Now switch to Randomized.",
    t3NoteRandomHtml: "<b>Randomized: the slope comes back to about 2 on average.</b> Click Draw a new sample a few times: it now scatters around 2 instead of sitting above it. The drift no longer lines up with x, so it can't hide in the slope. It becomes extra scatter (and lifts the whole line a little), and the run-order plot now shows it plainly as a rising trend. Randomizing doesn't remove drift; it makes it harmless and visible.",

    // Trial 4
    t4Num: "Trial 4 of 4",
    t4Title: "What actually fixes noise in x",
    t4Intro: "Two remedies. One is a different fitting method that allows for error in both x and y (orthogonal distance or Deming regression). The other is a design choice: test over a wider range of x, so the noise is small compared with how much x varies.",
    t4SxLabel: "Noise in x readings",
    t4SpanLabel: "Range of x tested",
    t4SpanHelp: "Wider range, same noise.",
    spanFmt: "0 to {s}",
    roOls: "Ordinary fit",
    roDem: "Errors-in-x fit",
    roExpected: "Ordinary fit expected at",
    expectedFmt: "{v} ({p}%)",
    t4ScatterAria: "Data with the true line, ordinary fit and errors-in-x fit",
    t4ScatterCapHtml: "<b>Three lines, one dataset.</b> 60 readings.",
    t4NoteExactHtml: "<b>With x read accurately, all three lines agree.</b> The corrected method only earns its keep when x is noisy.",
    t4NoteNoisyHtml: "<b>The blue errors-in-x fit lands near 2.00; the red ordinary fit lands near {exp}.</b> Now leave the noise alone and widen the range of x: the red line climbs back toward the truth, because the same noise is small next to a big spread. Two catches with the blue fit: it wobbles more from sample to sample (click Draw a new sample a few times), and it needs a fair estimate of each sensor's noise, from a datasheet or repeated readings.",
    t4NoteUnreliableHtml: " <b>At this setting the correction itself is unreliable:</b> the noise swamps the spread of x, so the blue slope can land far from 2, even negative. Widen the range before trusting any fit.",
    codeSummary: "Show the Python for this fit",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Noise in y costs precision. Noise in x costs accuracy.</b> An ordinary fit assumes x is exact; when it isn't, the slope is pulled toward zero.",
    take2Html: "<b>The residual plot cannot catch this.</b> The fit adjusts itself so the leftovers look balanced against x. You find this problem by asking how the data was produced.",
    take3Html: "<b>More data makes it worse, in a way.</b> The spread shrinks around the wrong answer, and the error bars grow confident while missing the truth.",
    take4Html: "<b>The cheapest fixes happen before you collect data:</b> randomize run order, log what might drift, read x with a better instrument, and test over a wide range.",
    checkTitle: "Three questions to ask about any fit",
    check1Title: "Is x really exact?",
    check1Body: "Compare the x sensor's error with the standard deviation of your x values (about 2.9 for x spread evenly over 0 to 10). If the error is more than about a third of that, expect the slope 10% or more too flat.",
    check2Title: "What changed during the session?",
    check2Body: "Temperature, supply voltage, warm-up, wear. If it moves with x, it hides inside your slope.",
    check3Title: "Does y ever push back on x?",
    check3Body: "In closed-loop tests a controller sets x based on y, so the two are tangled by design.",
    nameNoteHtml: "<b>The name for all of this:</b> statisticians call it <i>endogeneity</i>, meaning the error in y is related to x. Heteroskedasticity is a different problem (uneven scatter) that does show in the residual plot and leaves the slope unbiased. It has its own module, Uneven scatter.",
    footNote: "Simulated data. True model: y = 1 + 2x + error. Built for engineering students; no statistics background assumed.",
    footRead: "Further reading: Deming (1943), Statistical Adjustment of Data; Fuller (1987), Measurement Error Models."
  },
  es: {
    pageTitle: "El sesgo invisible · Cómo leer tus ajustes de curvas",
    eyebrow: "Cómo leer tus ajustes de curvas · Módulo 5",
    h1: "El sesgo invisible",
    lead: "La mayoría de los problemas de un ajuste dejan huellas en la gráfica de residuos. Este no. La recta ajustada sale mal, los residuos se ven perfectamente sanos, y tomar más datos te da más confianza en la respuesta equivocada.",
    introHtml: "Piensa en x como algo que lees en un instrumento (la temperatura de un termopar, un sensor de desplazamiento, un voltaje medido) y en y como la respuesta que registras. Todos los datos de esta página son simulados, así que conocemos la pendiente verdadera: <b>2,00</b>.",
    introSetpointHtml: "<b>Leer, no fijar.</b> Si fijas x con una perilla y anotas el valor fijado, es el valor verdadero el que varía alrededor de lo que fijaste. Ese es otro tipo de error, y no sesga la pendiente. Este módulo trata de valores de x que <i>lees</i>.",
    keyAria: "Leyenda de colores",
    keyTruth: "La verdad",
    keyFit: "Lo que reporta un ajuste por mínimos cuadrados ordinarios",
    keyFix: "Una estimación corregida",
    keyPts: "Puntos medidos",
    takeLabel: "Llévatelo:",
    takeSlides: "Diapositivas",
    takePy: "Script de Python",
    takePlay: "Juega con el código (en inglés)",
    takeColab: "Abrir en Colab (en inglés)",

    // Trial 1
    t1Num: "Prueba 1 de 4",
    t1Title: "Ruido en y frente a ruido en x",
    t1Intro: "Los dos deslizadores le agregan error aleatorio a un sensor. Solo uno de ellos inclina la recta.",
    quizPromptHtml: "<b>Primero, predice.</b> Si el sensor que lee x se vuelve más ruidoso, la pendiente ajustada…",
    quizAria: "Tu predicción",
    quizSteeper: "se vuelve más empinada",
    quizFlatter: "se vuelve más plana",
    quizSame: "queda igual, solo más desordenada",
    quizRightHtml: "<b>Correcto: más plana.</b> ",
    quizWrongHtml: "<b>Se vuelve más plana.</b> ",
    quizExplain: "El ruido en x esparce los puntos hacia los lados, y eso hace que la nube se vea menos empinada de lo que es. Pruébalo: sube el deslizador de x y mira cómo la recta roja se inclina hacia la horizontal; luego sube el de y y mira cómo, en promedio, se queda en su lugar.",
    t1SyLabel: "Ruido en las lecturas de y",
    t1SyHelp: "Desviación estándar del error del sensor de y.",
    t1SxLabel: "Ruido en las lecturas de x",
    t1SxHelp: "Desviación estándar del error del sensor de x. Para comparar: los valores verdaderos de x (repartidos de forma pareja entre 0 y 10) tienen una desviación estándar de unos 2,9.",
    btnNewSample: "Generar datos nuevos",
    roTrue: "Pendiente verdadera",
    roFitted: "Pendiente ajustada",
    roOff: "Diferencia",
    offSmall: "menos del 2%",
    offFlat: "{p}% más plana",
    offSteep: "{p}% más empinada",
    t1ScatterAria: "y medida contra x medida, con la recta verdadera y la recta ajustada",
    t1ScatterCapHtml: "<b>Los datos y el ajuste.</b> 50 lecturas.",
    t1ResidAria: "Residuos contra valores ajustados",
    t1ResidCapHtml: "<b>Gráfica de residuos.</b> El error que sobra después del ajuste, contra el valor ajustado.",
    axMeasuredX: "x medida",
    axMeasuredY: "y medida",
    axFittedY: "y ajustada",
    axResidual: "residuo",
    t1NoteExactHtml: "<b>Si x se lee con exactitud, el ajuste rojo cae sobre la verdad</b> hagas lo que hagas con el ruido en y. Más ruido en y solo engorda la nube y ensancha la banda de residuos.",
    t1NoteNoisyHtml: "<b>Con un ruido en x de {sx}, un ajuste ordinario baja en promedio a alrededor del {pct}% de la pendiente verdadera.</b> Ahora mira la gráfica de residuos: una banda plana y pareja alrededor de cero, justo como se ve un ajuste sano. No hay nada en ella que te avise.",

    // Trial 2
    t2Num: "Prueba 2 de 4",
    t2Title: "¿Lo arreglan más datos?",
    t2Intro: "Aquí el mismo experimento se repite 400 veces. Cada barra cuenta cuántas repeticiones dieron cierta pendiente. Las barras de error del 95% que calcula el software deberían contener la pendiente verdadera en el 95% de las repeticiones.",
    t2SxLabel: "Ruido en las lecturas de x",
    t2NLabel: "Puntos por experimento",
    t2Btn: "Repetir las 400 otra vez",
    roAvg: "Pendiente ajustada promedio",
    roMiddle: "95% central de los ajustes",
    roCaught: "Barras de error que contienen 2,00",
    rangeFmt: "{lo} a {hi}",
    coverFmt: "{p}% (debería ser 95%)",
    t2HistAria: "Histograma de las pendientes ajustadas en 400 experimentos repetidos",
    t2HistCapHtml: "<b>Pendientes ajustadas en 400 repeticiones.</b> La línea discontinua es la verdad; la línea roja es el ajuste promedio.",
    axFittedSlope: "pendiente ajustada",
    axRepeats: "número de repeticiones",
    lblTruth: "verdad {v}",
    lblAvg: "ajuste promedio {v}",
    t2NoteExactHtml: "<b>Sin ruido en x, las repeticiones se centran en 2,00,</b> y agregar puntos solo angosta el montón alrededor de la verdad. Las barras de error la contienen alrededor del 95% de las veces, como prometen.",
    t2NoteNoisyHtml: "<b>Prueba con 10, 100 y 1000 puntos.</b> El montón se angosta, pero sigue centrado cerca de {mean}, no de 2,00. ",
    t2NoteLowCoverHtml: "Con {n} puntos, las barras de error del 95% del software contienen la pendiente verdadera solo en el {cover}% de las repeticiones. Más datos te dan más certeza en la respuesta equivocada.",
    t2NoteOkCoverHtml: "Con {n} puntos, las barras de error todavía contienen 2,00 en el {cover}% de las repeticiones, porque la dispersión sigue siendo grande al lado del sesgo. Elige más puntos y mira cómo baja ese número.",

    // Trial 3
    t3Num: "Prueba 3 de 4",
    t3Title: "Algo que no mediste",
    t3Intro: "Durante la sesión, algo va derivando hacia arriba: el cuarto se calienta, una batería se descarga, un rodamiento se calienta. Empuja cada lectura de y un poco más a medida que pasa el tiempo. Nunca lo mediste.",
    t3DLabel: "Deriva durante la sesión",
    t3DHelp: "Cuánto le sumó la deriva a y al llegar a la última medición.",
    t3OrderLabel: "Orden de las mediciones",
    t3Sweep: "x de menor a mayor",
    t3Random: "Aleatorio",
    t3ScatterAria: "y contra x, con los puntos sombreados según cuándo se tomaron",
    t3ScatterCapHtml: "<b>Los datos y el ajuste.</b> Los puntos sólidos se tomaron después; los tenues, antes.",
    t3ResidAria: "Residuos contra el orden de medición",
    t3ResidCapHtml: "<b>Residuos en orden de medición.</b> La revisión para cualquier cosa que cambie con el tiempo.",
    axXSetting: "valor fijado de x",
    axRunNumber: "número de medición (orden en el tiempo)",
    t3NoteNoneHtml: "<b>Sin deriva, no hay problema.</b> Sube la deriva y compara los dos órdenes de medición.",
    t3NoteSweepHtml: "<b>Barrer x de menor a mayor ata la deriva a x.</b> El ajuste no puede distinguirlas, así que la deriva se mete en la pendiente. Los residuos en orden de medición parecen ruido común y corriente porque la deriva se absorbió junto con x. Ahora cambia a Aleatorio.",
    t3NoteRandomHtml: "<b>Aleatorio: la pendiente vuelve a ser más o menos 2 en promedio.</b> Haz clic en Generar datos nuevos unas cuantas veces: ahora se dispersa alrededor de 2 en vez de quedarse por encima. La deriva ya no se alinea con x, así que no puede esconderse en la pendiente. Se convierte en dispersión extra (y sube un poco toda la recta), y ahora la gráfica en orden de medición la muestra claramente como una tendencia que sube. Aleatorizar no elimina la deriva; la vuelve inofensiva y visible.",

    // Trial 4
    t4Num: "Prueba 4 de 4",
    t4Title: "Lo que de verdad corrige el ruido en x",
    t4Intro: "Dos remedios. Uno es otro método de ajuste que admite error tanto en x como en y (distancia ortogonal o regresión de Deming). El otro es una decisión de diseño: probar en un rango más amplio de x, para que el ruido sea pequeño comparado con cuánto varía x.",
    t4SxLabel: "Ruido en las lecturas de x",
    t4SpanLabel: "Rango de x probado",
    t4SpanHelp: "Rango más amplio, mismo ruido.",
    spanFmt: "0 a {s}",
    roOls: "Ajuste ordinario",
    roDem: "Ajuste con errores en x",
    roExpected: "Valor esperado del ajuste ordinario",
    expectedFmt: "{v} ({p}%)",
    t4ScatterAria: "Datos con la recta verdadera, el ajuste ordinario y el ajuste con errores en x",
    t4ScatterCapHtml: "<b>Tres rectas, un solo conjunto de datos.</b> 60 lecturas.",
    t4NoteExactHtml: "<b>Si x se lee con exactitud, las tres rectas coinciden.</b> El método corregido solo vale la pena cuando x tiene ruido.",
    t4NoteNoisyHtml: "<b>El ajuste azul con errores en x cae cerca de 2,00; el ajuste ordinario rojo cae cerca de {exp}.</b> Ahora deja el ruido como está y amplía el rango de x: la recta roja vuelve a subir hacia la verdad, porque el mismo ruido es pequeño al lado de una gran dispersión. El ajuste azul tiene dos inconvenientes: varía más de una muestra a otra (haz clic en Generar datos nuevos unas cuantas veces), y necesita una estimación razonable del ruido de cada sensor, de una hoja de datos o de lecturas repetidas.",
    t4NoteUnreliableHtml: " <b>Con este valor, la corrección misma no es confiable:</b> el ruido tapa la dispersión de x, así que la pendiente azul puede caer lejos de 2, incluso en negativo. Amplía el rango antes de confiar en cualquier ajuste.",
    codeSummary: "Ver el código en Python de este ajuste (en inglés)",

    // Takeaways
    takeTitle: "Para recordar",
    take1Html: "<b>El ruido en y cuesta precisión. El ruido en x cuesta exactitud.</b> Un ajuste ordinario supone que x es exacta; cuando no lo es, la pendiente se va hacia cero.",
    take2Html: "<b>La gráfica de residuos no puede detectar esto.</b> El ajuste se acomoda solo para que los residuos se vean equilibrados respecto de x. Este problema se descubre preguntándose cómo se produjeron los datos.",
    take3Html: "<b>En cierto sentido, más datos lo empeoran.</b> La dispersión se achica alrededor de la respuesta equivocada, y las barras de error se vuelven más seguras mientras se les escapa la verdad.",
    take4Html: "<b>Las soluciones más baratas ocurren antes de tomar los datos:</b> aleatoriza el orden de medición, registra lo que pueda derivar, lee x con un instrumento mejor y prueba en un rango amplio.",
    checkTitle: "Tres preguntas para cualquier ajuste",
    check1Title: "¿De verdad x es exacta?",
    check1Body: "Compara el error del sensor de x con la desviación estándar de tus valores de x (unos 2,9 para x repartida de forma pareja entre 0 y 10). Si el error es mayor que más o menos un tercio de eso, espera una pendiente un 10% o más demasiado plana.",
    check2Title: "¿Qué cambió durante la sesión?",
    check2Body: "La temperatura, el voltaje de la fuente, el calentamiento del equipo, el desgaste. Si se mueve junto con x, se esconde dentro de tu pendiente.",
    check3Title: "¿La y alguna vez influye en la x?",
    check3Body: "En las pruebas de lazo cerrado, un controlador fija x a partir de y, así que las dos quedan enredadas por diseño.",
    nameNoteHtml: "<b>El nombre de todo esto:</b> los estadísticos lo llaman <i>endogeneidad</i>, que significa que el error en y está relacionado con x. La heterocedasticidad es otro problema (dispersión desigual), que sí se ve en la gráfica de residuos y no sesga la pendiente. Tiene su propio módulo: Dispersión desigual.",
    footNote: "Datos simulados. Modelo verdadero: y = 1 + 2x + error. Hecho para estudiantes de ingeniería; no hace falta saber estadística.",
    footRead: "Lecturas recomendadas: Deming (1943), Statistical Adjustment of Data; Fuller (1987), Measurement Error Models."
  },
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Deming regression", es: "regresión de Deming" }, href: "https://openlibrary.org/books/OL6456639M/Statistical_adjustment_of_data" },
    { phrase: { en: "Statistical Adjustment of Data", es: "Statistical Adjustment of Data" }, href: "https://openlibrary.org/books/OL6456639M/Statistical_adjustment_of_data" },
    { phrase: { en: "Measurement Error Models", es: "Measurement Error Models" }, href: "https://openlibrary.org/books/OL2733911M/Measurement_error_models" }
  ]
};
