// strings.js — The Invisible Bias (Reading Your Fits, Module 5).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js. `es` is filled in during the Spanish pass;
// until then the page has no data-es-ready and renders English.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "The Invisible Bias · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 5",
    h1: "The Invisible Bias",
    lead: "Most fitting problems leave fingerprints in the residual plot. This one doesn't. The fitted line comes out wrong, the leftovers look perfectly healthy, and taking more data makes you more confident in the wrong answer.",
    introHtml: "Think of x as something you read off an instrument (a thermocouple temperature, a displacement sensor, a measured voltage) and y as the response you record. All data here is simulated, so we know the true slope: <b>2.00</b>.",
    introSetpointHtml: "<b>Reading, not setting.</b> If you set x on a dial and write down the setting, the true value wanders around your setting instead. That is a different kind of error, and it does not bias the slope. This module is about x values you <i>read</i>.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "What an ordinary least-squares fit reports",
    keyFix: "A corrected estimate",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",

    // Trial 1
    t1Num: "Trial 1 of 4",
    t1Title: "Noise in y versus noise in x",
    t1Intro: "Both sliders add random error to a sensor. Only one of them tilts the line.",
    quizPromptHtml: "<b>Predict first.</b> If the sensor that reads x gets noisier, the fitted slope will…",
    quizAria: "Your prediction",
    quizSteeper: "get steeper",
    quizFlatter: "get flatter",
    quizSame: "stay the same, just messier",
    quizRightHtml: "<b>Right: flatter.</b> ",
    quizWrongHtml: "<b>It gets flatter.</b> ",
    quizExplain: "Noise in x spreads the points sideways, which makes the cloud look less steep than it is. Try it: push the x slider up and watch the red line tip toward horizontal, then push the y slider and watch it stay put on average.",
    t1SyLabel: "Noise in y readings",
    t1SyHelp: "Standard deviation of the y sensor's error.",
    t1SxLabel: "Noise in x readings",
    t1SxHelp: "Standard deviation of the x sensor's error. For comparison, the true x values (spread evenly over 0 to 10) have a standard deviation of about 2.9.",
    btnNewSample: "Draw a new sample",
    roTrue: "True slope",
    roFitted: "Fitted slope",
    roOff: "Off by",
    offSmall: "under 2%",
    offFlat: "{p}% too flat",
    offSteep: "{p}% too steep",
    t1ScatterAria: "Measured y versus measured x with the true line and the fitted line",
    t1ScatterCapHtml: "<b>The data and the fit.</b> 50 readings.",
    t1ResidAria: "Residuals versus fitted values",
    t1ResidCapHtml: "<b>Residual plot.</b> Leftover error after the fit, against the fitted value.",
    axMeasuredX: "measured x",
    axMeasuredY: "measured y",
    axFittedY: "fitted y",
    axResidual: "residual",
    t1NoteExactHtml: "<b>With x read accurately, the red fit sits on the truth</b> whatever you do to the y noise. More y noise only fattens the cloud and widens the residual band.",
    t1NoteNoisyHtml: "<b>With x noise at {sx}, an ordinary fit is pulled to about {pct}% of the true slope on average.</b> Now look at the residual plot: a flat, even band around zero, exactly what a healthy fit looks like. Nothing in it warns you.",

    // Trial 2
    t2Num: "Trial 2 of 4",
    t2Title: "Will more data fix it?",
    t2Intro: "Here the same experiment is repeated 400 times. Each bar counts how many repeats got a given slope. The software's 95% error bars should contain the true slope in 95% of repeats.",
    t2SxLabel: "Noise in x readings",
    t2NLabel: "Points per experiment",
    t2Btn: "Repeat all 400 again",
    roAvg: "Average fitted slope",
    roMiddle: "Middle 95% of fits",
    roCaught: "Error bars that caught 2.00",
    rangeFmt: "{lo} to {hi}",
    coverFmt: "{p}% (should be 95%)",
    t2HistAria: "Histogram of fitted slopes from 400 repeated experiments",
    t2HistCapHtml: "<b>Fitted slopes from 400 repeats.</b> Dashed line is the truth; red line is the average fit.",
    axFittedSlope: "fitted slope",
    axRepeats: "number of repeats",
    lblTruth: "truth {v}",
    lblAvg: "average fit {v}",
    t2NoteExactHtml: "<b>No x noise: the repeats center on 2.00,</b> and adding points just narrows the pile around the truth. The error bars catch it about 95% of the time, as promised.",
    t2NoteNoisyHtml: "<b>Click through 10, 100, 1000 points.</b> The pile gets narrower but stays centered near {mean}, not 2.00. ",
    t2NoteLowCoverHtml: "At {n} points the software's 95% error bars catch the true slope in only {cover}% of repeats. More data makes you more certain of the wrong answer.",
    t2NoteOkCoverHtml: "At {n} points the error bars still catch 2.00 in {cover}% of repeats, because the scatter is still wide next to the bias. Pick more points and watch that number fall.",

    // Trial 3
    t3Num: "Trial 3 of 4",
    t3Title: "Something you didn't measure",
    t3Intro: "During the session, something drifts upward: the room warms, a battery sags, a bearing heats up. It nudges every y reading a little more as time goes on. You never measured it.",
    t3DLabel: "Drift over the session",
    t3DHelp: "How much the drift has added to y by the last run.",
    t3OrderLabel: "Order of the runs",
    t3Sweep: "Low to high x",
    t3Random: "Randomized",
    t3ScatterAria: "y versus x, points shaded by when they were taken",
    t3ScatterCapHtml: "<b>The data and the fit.</b> Solid points were taken later; faint ones earlier.",
    t3ResidAria: "Residuals versus run order",
    t3ResidCapHtml: "<b>Residuals in run order.</b> The check for anything that changes with time.",
    axXSetting: "x setting",
    axRunNumber: "run number (time order)",
    t3NoteNoneHtml: "<b>No drift, no problem.</b> Turn the drift up and compare the two run orders.",
    t3NoteSweepHtml: "<b>Sweeping x from low to high ties the drift to x.</b> The fit can't tell them apart, so the drift is folded into the slope. The run-order residuals look like plain noise because the drift was absorbed along with x. Now switch to Randomized.",
    t3NoteRandomHtml: "<b>Randomized: the slope comes back to about 2 on average.</b> Click Draw a new sample a few times: it now scatters around 2 instead of sitting above it. The drift no longer lines up with x, so it can't hide in the slope. It becomes extra scatter (and lifts the whole line a little), and the run-order plot now shows it plainly as a rising trend. Randomizing doesn't remove drift; it makes it harmless and visible.",

    // Trial 4
    t4Num: "Trial 4 of 4",
    t4Title: "What actually fixes noise in x",
    t4Intro: "Two remedies. One is a different fitting method that allows for error in both x and y (orthogonal distance or Deming regression). The other is a design choice: test over a wider range of x, so the noise is small compared with how much x varies.",
    t4SxLabel: "Noise in x readings",
    t4SpanLabel: "Range of x tested",
    t4SpanHelp: "Wider range, same noise.",
    spanFmt: "0 to {s}",
    roOls: "Ordinary fit",
    roDem: "Errors-in-x fit",
    roExpected: "Ordinary fit expected at",
    expectedFmt: "{v} ({p}%)",
    t4ScatterAria: "Data with the true line, ordinary fit and errors-in-x fit",
    t4ScatterCapHtml: "<b>Three lines, one dataset.</b> 60 readings.",
    t4NoteExactHtml: "<b>With x read accurately, all three lines agree.</b> The corrected method only earns its keep when x is noisy.",
    t4NoteNoisyHtml: "<b>The blue errors-in-x fit lands near 2.00; the red ordinary fit lands near {exp}.</b> Now leave the noise alone and widen the range of x: the red line climbs back toward the truth, because the same noise is small next to a big spread. Two catches with the blue fit: it wobbles more from sample to sample (click Draw a new sample a few times), and it needs a fair estimate of each sensor's noise, from a datasheet or repeated readings.",
    t4NoteUnreliableHtml: " <b>At this setting the correction itself is unreliable:</b> the noise swamps the spread of x, so the blue slope can land far from 2, even negative. Widen the range before trusting any fit.",
    codeSummary: "Show the Python for this fit",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Noise in y costs precision. Noise in x costs accuracy.</b> An ordinary fit assumes x is exact; when it isn't, the slope is pulled toward zero.",
    take2Html: "<b>The residual plot cannot catch this.</b> The fit adjusts itself so the leftovers look balanced against x. You find this problem by asking how the data was produced.",
    take3Html: "<b>More data makes it worse, in a way.</b> The spread shrinks around the wrong answer, and the error bars grow confident while missing the truth.",
    take4Html: "<b>The cheapest fixes happen before you collect data:</b> randomize run order, log what might drift, read x with a better instrument, and test over a wide range.",
    checkTitle: "Three questions to ask about any fit",
    check1Title: "Is x really exact?",
    check1Body: "Compare the x sensor's error with the standard deviation of your x values (about 2.9 for x spread evenly over 0 to 10). If the error is more than about a third of that, expect the slope 10% or more too flat.",
    check2Title: "What changed during the session?",
    check2Body: "Temperature, supply voltage, warm-up, wear. If it moves with x, it hides inside your slope.",
    check3Title: "Does y ever push back on x?",
    check3Body: "In closed-loop tests a controller sets x based on y, so the two are tangled by design.",
    nameNoteHtml: "<b>The name for all of this:</b> statisticians call it <i>endogeneity</i>, meaning the error in y is related to x. Heteroskedasticity is a different problem (uneven scatter) that does show in the residual plot and leaves the slope unbiased. It has its own module, Uneven scatter.",
    footNote: "Simulated data. True model: y = 1 + 2x + error. Built for engineering students; no statistics background assumed."
  },
  es: {}
};
