// strings.js — Reading a residual plot (Reading Your Fits, Module 2).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Reading a Residual Plot · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 2",
    h1: "Reading a Residual Plot",
    lead: "After you fit a line, the leftovers are the most useful thing on your screen. A handful of shapes tell you almost everything that can go wrong with the fit.",
    introHtml: "A <b>residual</b> is the vertical gap between a point and the fitted line: measured y minus fitted y. Plot the residuals against the fitted value, and again in the order you took the data, and look for shape. Healthy residuals are a flat, even band around zero. All data here is simulated, so the true model is known.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The fitted line",
    keyFix: "A better fit (right shape), or the fit without your point",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",
    takePlay: "Play with the code",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "The pattern gallery",
    t1Intro: "Pick a hidden problem and turn it up. Watch what it does to the residual plot, and try both ways of plotting the residuals.",
    t1ProblemLabel: "Hidden problem",
    pNone: "None",
    pCurve: "Curve",
    pFan: "Fan",
    pDrift: "Drift",
    pOutlier: "Outlier",
    t1SevLabel: "How strong",
    t1SevHelp: "0 = no problem at all, 1 = hard to miss.",
    t1AxisLabel: "Plot residuals against",
    axisFitted: "Fitted value",
    axisOrder: "Run order",
    btnNewSample: "Draw a new sample",
    roSlope: "Fitted slope",
    roTrueSlope: "True slope",
    roR2: "R²",
    t1ScatterAria: "Data and the fitted line",
    t1ScatterCapHtml: "<b>The data and the fit.</b> 40 readings, taken in random x order.",
    t1ResidAria: "Residual plot",
    t1ResidCapFittedHtml: "<b>Residuals against the fitted value.</b> Checks shape and spread.",
    t1ResidCapOrderHtml: "<b>Residuals in the order the data was taken.</b> Checks for anything that changed with time.",
    axMeasuredX: "measured x",
    axMeasuredY: "measured y",
    axFittedY: "fitted y",
    axResidual: "residual",
    axRunNumber: "run number (time order)",
    t1NoteWeakHtml: "<b>At this strength the problem is buried in the noise.</b> Turn it up until you can see it, then turn it back down to find the point where you'd miss it.",
    t1NoteNoneHtml: "<b>This is what healthy looks like:</b> a flat, even band around zero with no shape, whichever way you plot it. The line has the right shape, the scatter is even, and nothing drifted.",
    t1NoteCurveHtml: "<b>The residuals bend:</b> above zero at both ends and below in the middle (or the reverse). The line is the wrong shape for the data. Fit the shape the physics gives you; Trial 2 shows how.",
    t1NoteFanHtml: "<b>The band widens as the fitted value grows.</b> The line itself is fine, but its error bars are not, because the scatter isn't the same everywhere. That's uneven scatter, Module 3.",
    t1NoteDriftFittedHtml: "<b>Against the fitted value this looks almost healthy.</b> Switch the plot to Run order.",
    t1NoteDriftOrderHtml: "<b>In run order the leftovers climb.</b> Something changed during the session (warm-up, a drifting room, a sagging supply) and nudged every later reading. That's time-ordered data, Module 4.",
    t1NoteOutlierHtml: "<b>One point sits far from the band.</b> Check your notes for that run first: a loose fixture, a saturated sensor, a typo. Trial 3 shows when one point is enough to move the whole line.",

    quizTitle: "Name that pattern",
    quizIntroHtml: "<b>Mystery dataset.</b> Both residual plots, no labels. Which problem is hiding in it?",
    quizFittedCap: "Against fitted value",
    quizOrderCap: "In run order",
    quizAria: "Your answer",
    quizNew: "New mystery",
    quizRightHtml: "<b>Right: {name}.</b> ",
    quizWrongHtml: "<b>Not quite; it was {name}.</b> ",
    quizScore: "{right} of {total} right",
    quizWhyNone: "No shape in either plot.",
    quizWhyCurve: "The fitted-value plot bends.",
    quizWhyFan: "The fitted-value plot widens to one side.",
    quizWhyDrift: "Only the run-order plot shows it: the leftovers climb over time.",
    quizWhyOutlier: "One point sits far from the rest in both plots.",
    quizMysteryAria1: "Mystery residuals against fitted value",
    quizMysteryAria2: "Mystery residuals in run order",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "When the shape is wrong",
    t2Intro: "A thermocouple at 80 °C is dropped into a 22 °C room and logged every 15 seconds. Physics says it cools exponentially toward room temperature. Fit a straight line anyway and read the residuals.",
    t2ModelLabel: "Model",
    modelLine: "Straight line",
    modelExp: "Exponential",
    t2NoiseLabel: "Sensor noise",
    t2WindowLabel: "Stop recording after",
    t2WindowHelp: "A short recording hides the curve.",
    unitC: "{v} °C",
    unitMin: "{v} min",
    roS: "Residual SD",
    roTau: "Fitted time constant",
    roTrueTau: "True time constant",
    dash: "–",
    t2DataAria: "Temperature against time with the fitted curve",
    t2DataCapHtml: "<b>Cooling curve and the fit.</b>",
    t2ResidAria: "Residuals against time",
    t2ResidCapHtml: "<b>Residuals in time order.</b>",
    axTime: "time (min)",
    axTemp: "temperature (°C)",
    axResidC: "residual (°C)",
    t2NoteLineHtml: "<b>R² is {r2}, and yet the residuals form a clear U.</b> The straight line runs above the data in the middle and below it at the ends, every time. A high R² doesn't mean the shape is right. Now shorten the recording to 3 min and raise the noise to 2 °C: the U shrinks until the noise hides it.",
    t2NoteLineHiddenHtml: "<b>R² is {r2}, and the U is now about the size of the noise.</b> Over a short window with a noisy sensor the curve looks straight, so the residuals look healthy. The model is still the wrong shape; this data just can't show it. The physics, or a longer recording, is what catches it.",
    t2NoteExpHtml: "<b>The exponential leaves a flat, even band.</b> The residual SD ({s} °C) matches the sensor noise, and the time constant comes out at {tau} min against a true 4.0. When the model has the right shape, the leftovers are just noise.",
    t2NoteExpShortHtml: "<b>The shape is right, but this recording can't pin down the time constant.</b> It came out at {tau} min against a true 4.0. With only {win} min of data and this much noise, a wide range of time constants fit about equally well. Draw a few new samples to see how far it jumps, then record longer, until the curve has flattened out.",
    t2NoteExpNoNoiseHtml: "<b>With no sensor noise the exponential fits exactly.</b> The residuals are zero, and the time constant comes out at {tau} min against a true 4.0.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "One point steering the line",
    t3Intro: "Twenty well-behaved readings, plus one you control. Move it far out in x, off the line, or both, and watch how much the fit follows it.",
    t3XLabel: "Its x position",
    t3YLabel: "Its distance from the true line",
    t3YHelp: "In y units, above (+) or below (−) the truth.",
    roWith: "Slope with the point",
    roWithout: "Slope without it",
    roLev: "Leverage (flag above {typ})",
    roStud: "Studentized residual",
    roCook: "Cook's distance",
    t3DataAria: "Data with the fit including and excluding the controlled point",
    t3DataCapHtml: "<b>Red: fit with the point. Blue: fit without it.</b> The ringed point is yours.",
    t3CookAria: "Cook's distance for every point",
    t3CookCapHtml: "<b>Cook's distance for every point.</b> How much the whole fit moves if that point is removed. Dashed line: 4/n, a common flag.",
    axPoint: "point",
    axCook: "Cook's distance",
    t3NoteOrdinaryHtml: "<b>An ordinary point.</b> Close to the others in x and near the line, so it barely moves anything.",
    t3NoteLeverHtml: "<b>A lever point on the line.</b> It sits far out in x, so it <i>could</i> move the fit, but it agrees with everything else, so it simply steadies the slope. Far-out points that follow the trend are useful.",
    t3NoteOutlierHtml: "<b>An outlier within the range of the data.</b> It's far from the line, but plenty of points on either side hold the slope in place, so the slope moves only {d}% when you remove it. It still lifts or lowers the whole line, inflates the scatter and widens every error bar, which is why its Cook's distance can still be flagged.",
    t3NoteInfluentialHtml: "<b>An influential point: off the line and out toward the edge of the data.</b> It drags the fit toward itself; the slope changes {d}% when you remove it. Notice its residual looks smaller than its real miss, because the line bent toward it. That's why the checks use studentized residuals and Cook's distance, not the raw residual.",

    // Make one yourself
    makeSummary: "Make these plots yourself (Excel, MATLAB, Python)",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Make the same three checks after every fit:</b> residuals against the fitted value, residuals in run order, and a look for single points that stand out.",
    take2Html: "<b>Read them in order:</b> shape first (a wrong shape fakes the other patterns), then spread, then time order, then single points.",
    take3Html: "<b>Healthy is boring:</b> a flat, even band around zero with no shape. Anything else is a clue, not a verdict. Check the notes from the session before changing the model.",
    take4Html: "<b>A clean residual plot still can't catch everything.</b> Noise in your x readings and unmeasured drift can bias the slope and leave the residuals looking fine. That's Module 5.",
    patternsTitle: "The four patterns",
    pat1Title: "A bend",
    pat1Body: "Wrong shape. Fit the model the physics gives you.",
    pat2Title: "A fan",
    pat2Body: "Uneven scatter. The line is fine; the error bars aren't. Module 3.",
    pat3Title: "A trend in run order",
    pat3Body: "Something changed during the session. Module 4.",
    pat4Title: "One point far away",
    pat4Body: "Check the notes, then check its influence. Don't just delete it.",
    footNote: "Simulated data. Trials 1 and 3: y = 1 + 2x + error. Trial 2: T = 22 + 58·e^(−t/4) + error, in °C and minutes.",
    footRead: "Further reading: Cook (1977), \"Detection of Influential Observation in Linear Regression\"; Cook and Weisberg (1982), Residuals and Influence in Regression; the NIST/SEMATECH e-Handbook of Statistical Methods."
  },
  es: {
    pageTitle: "Cómo leer una gráfica de residuos · Cómo leer tus ajustes de curvas",
    eyebrow: "Cómo leer tus ajustes de curvas · Módulo 2",
    h1: "Cómo leer una gráfica de residuos",
    lead: "Después de ajustar una recta, lo que sobra es lo más útil que tienes en la pantalla. Un puñado de formas te dicen casi todo lo que puede salir mal con el ajuste.",
    introHtml: "Un <b>residuo</b> es la distancia vertical entre un punto y la recta ajustada: la y medida menos la y ajustada. Grafica los residuos contra el valor ajustado, y otra vez en el orden en que tomaste los datos, y busca alguna forma. Unos residuos sanos forman una banda plana y pareja alrededor de cero. Todos los datos de esta página son simulados, así que conocemos el modelo verdadero.",
    keyAria: "Leyenda de colores",
    keyTruth: "La verdad",
    keyFit: "La recta ajustada",
    keyFix: "Un ajuste mejor (con la forma correcta), o el ajuste sin tu punto",
    keyPts: "Puntos medidos",
    takeLabel: "Llévatelo:",
    takeSlides: "Diapositivas (en inglés)",
    takePy: "Script de Python",
    takePlay: "Juega con el código (en inglés)",

    // Trial 1
    t1Num: "Prueba 1 de 3",
    t1Title: "La galería de patrones",
    t1Intro: "Elige un problema oculto y súbele la intensidad. Mira qué le hace a la gráfica de residuos y prueba las dos formas de graficar los residuos.",
    t1ProblemLabel: "Problema oculto",
    pNone: "Ninguno",
    pCurve: "Curva",
    pFan: "Abanico",
    pDrift: "Deriva",
    pOutlier: "Atípico",
    t1SevLabel: "Intensidad",
    t1SevHelp: "0 = ningún problema, 1 = imposible no verlo.",
    t1AxisLabel: "Graficar los residuos contra",
    axisFitted: "Valor ajustado",
    axisOrder: "Orden de medición",
    btnNewSample: "Generar datos nuevos",
    roSlope: "Pendiente ajustada",
    roTrueSlope: "Pendiente verdadera",
    roR2: "R²",
    t1ScatterAria: "Datos y recta ajustada",
    t1ScatterCapHtml: "<b>Los datos y el ajuste.</b> 40 lecturas, tomadas con x en orden aleatorio.",
    t1ResidAria: "Gráfica de residuos",
    t1ResidCapFittedHtml: "<b>Residuos contra el valor ajustado.</b> Revisa la forma y la dispersión.",
    t1ResidCapOrderHtml: "<b>Residuos en el orden en que se tomaron los datos.</b> Revisa si algo cambió con el tiempo.",
    axMeasuredX: "x medida",
    axMeasuredY: "y medida",
    axFittedY: "y ajustada",
    axResidual: "residuo",
    axRunNumber: "número de medición (orden en el tiempo)",
    t1NoteWeakHtml: "<b>Con esta intensidad, el problema queda enterrado en el ruido.</b> Súbela hasta que lo veas y luego bájala para encontrar el punto en que ya no lo notarías.",
    t1NoteNoneHtml: "<b>Así se ve un ajuste sano:</b> una banda plana y pareja alrededor de cero, sin ninguna forma, la grafiques como la grafiques. La recta tiene la forma correcta, la dispersión es pareja y no hubo deriva.",
    t1NoteCurveHtml: "<b>Los residuos se curvan:</b> quedan por encima de cero en los dos extremos y por debajo en el medio (o al revés). La recta no tiene la forma de los datos. Ajusta la forma que te da la física; la Prueba 2 muestra cómo.",
    t1NoteFanHtml: "<b>La banda se ensancha a medida que crece el valor ajustado.</b> La recta en sí está bien, pero sus barras de error no, porque la dispersión no es igual en todas partes. Eso es dispersión desigual: Módulo 3.",
    t1NoteDriftFittedHtml: "<b>Contra el valor ajustado, esto se ve casi sano.</b> Cambia la gráfica a Orden de medición.",
    t1NoteDriftOrderHtml: "<b>En orden de medición, los residuos van subiendo.</b> Algo cambió durante la sesión (el equipo se estaba calentando, la temperatura del laboratorio se movía, la fuente de alimentación iba cayendo) y empujó cada lectura posterior. Son datos ordenados en el tiempo: Módulo 4.",
    t1NoteOutlierHtml: "<b>Un punto queda lejos de la banda.</b> Primero revisa tus notas de esa medición: un montaje flojo, un sensor saturado, un error al anotar. La Prueba 3 muestra cuándo basta un solo punto para mover toda la recta.",

    quizTitle: "Adivina el patrón",
    quizIntroHtml: "<b>Datos misteriosos.</b> Las dos gráficas de residuos, sin etiquetas. ¿Qué problema se esconde aquí?",
    quizFittedCap: "Contra el valor ajustado",
    quizOrderCap: "En orden de medición",
    quizAria: "Tu respuesta",
    quizNew: "Otro misterio",
    quizRightHtml: "<b>Correcto: {name}.</b> ",
    quizWrongHtml: "<b>No exactamente. La respuesta era: {name}.</b> ",
    quizScore: "{right} de {total} correctas",
    quizWhyNone: "No hay ninguna forma en las dos gráficas.",
    quizWhyCurve: "La gráfica contra el valor ajustado se curva.",
    quizWhyFan: "La gráfica contra el valor ajustado se abre hacia un lado.",
    quizWhyDrift: "Solo la gráfica en orden de medición lo muestra: los residuos suben con el tiempo.",
    quizWhyOutlier: "Un punto queda lejos del resto en las dos gráficas.",
    quizMysteryAria1: "Residuos misteriosos contra el valor ajustado",
    quizMysteryAria2: "Residuos misteriosos en orden de medición",

    // Trial 2
    t2Num: "Prueba 2 de 3",
    t2Title: "Cuando la forma está mal",
    t2Intro: "Un termopar a 80 °C se pasa a un cuarto a 22 °C y se registra su lectura cada 15 segundos. La física dice que se enfría de forma exponencial hacia la temperatura ambiente. Ajusta una recta de todos modos y lee los residuos.",
    t2ModelLabel: "Modelo",
    modelLine: "Recta",
    modelExp: "Exponencial",
    t2NoiseLabel: "Ruido del sensor",
    t2WindowLabel: "Dejar de registrar a los",
    t2WindowHelp: "Un registro corto esconde la curva.",
    unitC: "{v} °C",
    unitMin: "{v} min",
    roS: "Desv. estándar de los residuos",
    roTau: "Constante de tiempo ajustada",
    roTrueTau: "Constante de tiempo verdadera",
    dash: "–",
    t2DataAria: "Temperatura contra tiempo, con la curva ajustada",
    t2DataCapHtml: "<b>Curva de enfriamiento y ajuste.</b>",
    t2ResidAria: "Residuos contra tiempo",
    t2ResidCapHtml: "<b>Residuos en orden temporal.</b>",
    axTime: "tiempo (min)",
    axTemp: "temperatura (°C)",
    axResidC: "residuo (°C)",
    t2NoteLineHtml: "<b>R² es {r2} y, aun así, los residuos forman una U clara.</b> La recta pasa por encima de los datos en el medio y por debajo en los extremos, siempre. Un R² alto no significa que la forma sea correcta. Ahora acorta el registro a 3 min y sube el ruido a 2 °C: la U se achica hasta que el ruido la esconde.",
    t2NoteLineHiddenHtml: "<b>R² es {r2}, y ahora la U es más o menos del tamaño del ruido.</b> En una ventana corta y con un sensor ruidoso, la curva parece recta, así que los residuos se ven sanos. El modelo sigue teniendo la forma equivocada; lo que pasa es que estos datos no pueden mostrarlo. Lo que lo delata es la física, o un registro más largo.",
    t2NoteExpHtml: "<b>La exponencial deja una banda plana y pareja.</b> La desviación estándar de los residuos ({s} °C) coincide con el ruido del sensor, y la constante de tiempo sale {tau} min, frente a un valor verdadero de 4,0. Cuando el modelo tiene la forma correcta, lo que sobra es solo ruido.",
    t2NoteExpShortHtml: "<b>La forma es correcta, pero este registro no alcanza para fijar la constante de tiempo.</b> Salió {tau} min, frente a un valor verdadero de 4,0. Con solo {win} min de datos y tanto ruido, un rango amplio de constantes de tiempo ajusta casi igual de bien. Genera datos nuevos unas cuantas veces para ver cuánto salta y luego registra durante más tiempo, hasta que la curva se aplane.",
    t2NoteExpNoNoiseHtml: "<b>Sin ruido en el sensor, la exponencial ajusta exactamente.</b> Los residuos son cero y la constante de tiempo sale {tau} min, frente a un valor verdadero de 4,0.",

    // Trial 3
    t3Num: "Prueba 3 de 3",
    t3Title: "Un punto que dirige la recta",
    t3Intro: "Veinte lecturas bien portadas, más una que controlas tú. Llévala lejos en x, fuera de la recta o las dos cosas, y mira cuánto la sigue el ajuste.",
    t3XLabel: "Su posición en x",
    t3YLabel: "Su distancia a la recta verdadera",
    t3YHelp: "En unidades de y, por encima (+) o por debajo (−) de la recta verdadera.",
    roWith: "Pendiente con el punto",
    roWithout: "Pendiente sin él",
    roLev: "Apalancamiento (alerta si pasa de {typ})",
    roStud: "Residuo estudentizado",
    roCook: "Distancia de Cook",
    t3DataAria: "Datos con el ajuste con y sin el punto que controlas",
    t3DataCapHtml: "<b>Rojo: ajuste con el punto. Azul: ajuste sin él.</b> El punto con el anillo es el tuyo.",
    t3CookAria: "Distancia de Cook de cada punto",
    t3CookCapHtml: "<b>Distancia de Cook de cada punto.</b> Cuánto se mueve todo el ajuste si quitas ese punto. Línea discontinua: 4/n, un umbral de alerta común.",
    axPoint: "punto",
    axCook: "distancia de Cook",
    t3NoteOrdinaryHtml: "<b>Un punto común y corriente.</b> Está cerca de los demás en x y cerca de la recta, así que casi no mueve nada.",
    t3NoteLeverHtml: "<b>Un punto de alto apalancamiento sobre la recta.</b> Está lejos en x, así que <i>podría</i> mover el ajuste, pero coincide con todo lo demás, así que solo le da estabilidad a la pendiente. Los puntos lejanos que siguen la tendencia son útiles.",
    t3NoteOutlierHtml: "<b>Un valor atípico dentro del rango de los datos.</b> Está lejos de la recta, pero hay muchos puntos a cada lado que sostienen la pendiente, así que la pendiente cambia solo {d}% cuando lo quitas. Aun así sube o baja toda la recta, infla la dispersión y ensancha todas las barras de error; por eso su distancia de Cook todavía puede dar alerta.",
    t3NoteInfluentialHtml: "<b>Un punto influyente: fuera de la recta y hacia el borde de los datos.</b> Arrastra el ajuste hacia él; la pendiente cambia {d}% cuando lo quitas. Fíjate en que su residuo parece más pequeño de lo que el punto realmente se aleja, porque la recta se inclinó hacia él. Por eso las revisiones usan residuos estudentizados y la distancia de Cook, no el residuo tal cual.",

    // Make one yourself
    makeSummary: "Haz tú estas gráficas (Excel, MATLAB, Python; el código está en inglés)",

    // Takeaways
    takeTitle: "Para recordar",
    take1Html: "<b>Haz las mismas tres revisiones después de cada ajuste:</b> residuos contra el valor ajustado, residuos en orden de medición y una búsqueda de puntos sueltos que se destaquen.",
    take2Html: "<b>Léelas en orden:</b> primero la forma (una forma equivocada imita los otros patrones), luego la dispersión, luego el orden en el tiempo y al final los puntos sueltos.",
    take3Html: "<b>Lo sano es aburrido:</b> una banda plana y pareja alrededor de cero, sin forma. Cualquier otra cosa es una pista, no un veredicto. Revisa las notas de la sesión antes de cambiar el modelo.",
    take4Html: "<b>Una gráfica de residuos limpia no lo detecta todo.</b> El ruido en tus lecturas de x y una deriva que no mediste pueden sesgar la pendiente y dejar los residuos con buena cara. Eso es el Módulo 5.",
    patternsTitle: "Los cuatro patrones",
    pat1Title: "Una curvatura",
    pat1Body: "La forma está mal. Ajusta el modelo que te da la física.",
    pat2Title: "Un abanico",
    pat2Body: "Dispersión desigual. La recta está bien; las barras de error no. Módulo 3.",
    pat3Title: "Una tendencia en el orden de medición",
    pat3Body: "Algo cambió durante la sesión. Módulo 4.",
    pat4Title: "Un punto muy alejado",
    pat4Body: "Revisa las notas y luego revisa su influencia. No lo borres sin más.",
    footNote: "Datos simulados. Pruebas 1 y 3: y = 1 + 2x + error. Prueba 2: T = 22 + 58·e^(−t/4) + error, en °C y minutos.",
    footRead: "Lecturas recomendadas: Cook (1977), \"Detection of Influential Observation in Linear Regression\"; Cook y Weisberg (1982), Residuals and Influence in Regression; el NIST/SEMATECH e-Handbook of Statistical Methods."
  },
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Cook's distance", es: "Distancia de Cook" }, href: "cook-1977.pdf" },
    { phrase: { en: "\"Detection of Influential Observation in Linear Regression\"", es: "\"Detection of Influential Observation in Linear Regression\"" }, href: "cook-1977.pdf" },
    { phrase: { en: "Residuals and Influence in Regression", es: "Residuals and Influence in Regression" }, href: "cook-weisberg-1982.pdf" },
    { phrase: { en: "NIST/SEMATECH e-Handbook of Statistical Methods", es: "NIST/SEMATECH e-Handbook of Statistical Methods" }, href: "https://www.itl.nist.gov/div898/handbook/index.htm" }
  ]
};
