// strings.js — Reading a residual plot (Reading Your Fits, Module 2).
// All display text for this page. Keys ending in "Html" may hold <b>/<i>/<code>.
// {name} placeholders are filled by main.js. `es` is filled in during the Spanish pass.
window.LEARN_STRINGS = {
  en: {
    pageTitle: "Reading a Residual Plot · Reading Your Fits",
    eyebrow: "Reading Your Fits · Module 2",
    h1: "Reading a Residual Plot",
    lead: "After you fit a line, the leftovers are the most useful thing on your screen. A handful of shapes tell you almost everything that can go wrong with the fit.",
    introHtml: "A <b>residual</b> is the vertical gap between a point and the fitted line: measured y minus fitted y. Plot the residuals against the fitted value, and again in the order you took the data, and look for shape. Healthy residuals are a flat, even band around zero. All data here is simulated, so the true model is known.",
    keyAria: "Color key",
    keyTruth: "The truth",
    keyFit: "The fitted line",
    keyFix: "A better fit (right shape), or the fit without your point",
    keyPts: "Measured points",
    takeLabel: "Take it with you:",
    takeSlides: "Slides",
    takePy: "Python script",

    // Trial 1
    t1Num: "Trial 1 of 3",
    t1Title: "The pattern gallery",
    t1Intro: "Pick a hidden problem and turn it up. Watch what it does to the residual plot, and try both ways of plotting the residuals.",
    t1ProblemLabel: "Hidden problem",
    pNone: "None",
    pCurve: "Curve",
    pFan: "Fan",
    pDrift: "Drift",
    pOutlier: "Outlier",
    t1SevLabel: "How strong",
    t1SevHelp: "0 = no problem at all, 1 = hard to miss.",
    t1AxisLabel: "Plot residuals against",
    axisFitted: "Fitted value",
    axisOrder: "Run order",
    btnNewSample: "Draw a new sample",
    roSlope: "Fitted slope",
    roTrueSlope: "True slope",
    roR2: "R²",
    t1ScatterAria: "Data and the fitted line",
    t1ScatterCapHtml: "<b>The data and the fit.</b> 40 readings, taken in random x order.",
    t1ResidAria: "Residual plot",
    t1ResidCapFittedHtml: "<b>Residuals against the fitted value.</b> Checks shape and spread.",
    t1ResidCapOrderHtml: "<b>Residuals in the order the data was taken.</b> Checks for anything that changed with time.",
    axMeasuredX: "measured x",
    axMeasuredY: "measured y",
    axFittedY: "fitted y",
    axResidual: "residual",
    axRunNumber: "run number (time order)",
    t1NoteWeakHtml: "<b>At this strength the problem is buried in the noise.</b> Turn it up until you can see it, then turn it back down to find the point where you'd miss it.",
    t1NoteNoneHtml: "<b>This is what healthy looks like:</b> a flat, even band around zero with no shape, whichever way you plot it. The line has the right shape, the scatter is even, and nothing drifted.",
    t1NoteCurveHtml: "<b>The residuals bend:</b> above zero at both ends and below in the middle (or the reverse). The line is the wrong shape for the data. Fit the shape the physics gives you; Trial 2 shows how.",
    t1NoteFanHtml: "<b>The band widens as the fitted value grows.</b> The line itself is fine, but its error bars are not, because the scatter isn't the same everywhere. That's uneven scatter, Module 3.",
    t1NoteDriftFittedHtml: "<b>Against the fitted value this looks almost healthy.</b> Switch the plot to Run order.",
    t1NoteDriftOrderHtml: "<b>In run order the leftovers climb.</b> Something changed during the session (warm-up, a drifting room, a sagging supply) and nudged every later reading. That's time-ordered data, Module 4.",
    t1NoteOutlierHtml: "<b>One point sits far from the band.</b> Check your notes for that run first: a loose fixture, a saturated sensor, a typo. Trial 3 shows when one point is enough to move the whole line.",

    quizTitle: "Name that pattern",
    quizIntroHtml: "<b>Mystery dataset.</b> Both residual plots, no labels. Which problem is hiding in it?",
    quizFittedCap: "Against fitted value",
    quizOrderCap: "In run order",
    quizAria: "Your answer",
    quizNew: "New mystery",
    quizRightHtml: "<b>Right: {name}.</b> ",
    quizWrongHtml: "<b>Not quite; it was {name}.</b> ",
    quizScore: "{right} of {total} right",
    quizWhyNone: "No shape in either plot.",
    quizWhyCurve: "The fitted-value plot bends.",
    quizWhyFan: "The fitted-value plot widens to one side.",
    quizWhyDrift: "Only the run-order plot shows it: the leftovers climb over time.",
    quizWhyOutlier: "One point sits far from the rest in both plots.",
    quizMysteryAria1: "Mystery residuals against fitted value",
    quizMysteryAria2: "Mystery residuals in run order",

    // Trial 2
    t2Num: "Trial 2 of 3",
    t2Title: "When the shape is wrong",
    t2Intro: "A thermocouple at 80 °C is dropped into a 22 °C room and logged every 15 seconds. Physics says it cools exponentially toward room temperature. Fit a straight line anyway and read the residuals.",
    t2ModelLabel: "Model",
    modelLine: "Straight line",
    modelExp: "Exponential",
    t2NoiseLabel: "Sensor noise",
    t2WindowLabel: "Stop recording after",
    t2WindowHelp: "A short recording hides the curve.",
    unitC: "{v} °C",
    unitMin: "{v} min",
    roS: "Residual SD",
    roTau: "Fitted time constant",
    roTrueTau: "True time constant",
    dash: "–",
    t2DataAria: "Temperature against time with the fitted curve",
    t2DataCapHtml: "<b>Cooling curve and the fit.</b>",
    t2ResidAria: "Residuals against time",
    t2ResidCapHtml: "<b>Residuals in time order.</b>",
    axTime: "time (min)",
    axTemp: "temperature (°C)",
    axResidC: "residual (°C)",
    t2NoteLineHtml: "<b>R² is {r2}, and yet the residuals form a clear U.</b> The straight line runs above the data in the middle and below it at the ends, every time. A high R² doesn't mean the shape is right. Now shorten the recording to 3 min and raise the noise to 2 °C: the U shrinks until the noise hides it.",
    t2NoteLineHiddenHtml: "<b>R² is {r2}, and the U is now about the size of the noise.</b> Over a short window with a noisy sensor the curve looks straight, so the residuals look healthy. The model is still the wrong shape; this data just can't show it. The physics, or a longer recording, is what catches it.",
    t2NoteExpHtml: "<b>The exponential leaves a flat, even band.</b> The residual SD ({s} °C) matches the sensor noise, and the time constant comes out at {tau} min against a true 4.0. When the model has the right shape, the leftovers are just noise.",
    t2NoteExpShortHtml: "<b>The shape is right, but this recording can't pin down the time constant.</b> It came out at {tau} min against a true 4.0. With only {win} min of data and this much noise, a wide range of time constants fit about equally well. Draw a few new samples to see how far it jumps, then record longer, until the curve has flattened out.",
    t2NoteExpNoNoiseHtml: "<b>With no sensor noise the exponential fits exactly.</b> The residuals are zero, and the time constant comes out at {tau} min against a true 4.0.",

    // Trial 3
    t3Num: "Trial 3 of 3",
    t3Title: "One point steering the line",
    t3Intro: "Twenty well-behaved readings, plus one you control. Move it far out in x, off the line, or both, and watch how much the fit follows it.",
    t3XLabel: "Its x position",
    t3YLabel: "Its distance from the true line",
    t3YHelp: "In y units, above (+) or below (−) the truth.",
    roWith: "Slope with the point",
    roWithout: "Slope without it",
    roLev: "Leverage (flag above {typ})",
    roStud: "Studentized residual",
    roCook: "Cook's distance",
    t3DataAria: "Data with the fit including and excluding the controlled point",
    t3DataCapHtml: "<b>Red: fit with the point. Blue: fit without it.</b> The ringed point is yours.",
    t3CookAria: "Cook's distance for every point",
    t3CookCapHtml: "<b>Cook's distance for every point.</b> How much the whole fit moves if that point is removed. Dashed line: 4/n, a common flag.",
    axPoint: "point",
    axCook: "Cook's distance",
    t3NoteOrdinaryHtml: "<b>An ordinary point.</b> Close to the others in x and near the line, so it barely moves anything.",
    t3NoteLeverHtml: "<b>A lever point on the line.</b> It sits far out in x, so it <i>could</i> move the fit, but it agrees with everything else, so it simply steadies the slope. Far-out points that follow the trend are useful.",
    t3NoteOutlierHtml: "<b>An outlier within the range of the data.</b> It's far from the line, but plenty of points on either side hold the slope in place, so the slope moves only {d}% when you remove it. It still lifts or lowers the whole line, inflates the scatter and widens every error bar, which is why its Cook's distance can still be flagged.",
    t3NoteInfluentialHtml: "<b>An influential point: off the line and out toward the edge of the data.</b> It drags the fit toward itself; the slope changes {d}% when you remove it. Notice its residual looks smaller than its real miss, because the line bent toward it. That's why the checks use studentized residuals and Cook's distance, not the raw residual.",

    // Make one yourself
    makeSummary: "Make these plots yourself (Excel, MATLAB, Python)",

    // Takeaways
    takeTitle: "What to take away",
    take1Html: "<b>Make the same three checks after every fit:</b> residuals against the fitted value, residuals in run order, and a look for single points that stand out.",
    take2Html: "<b>Read them in order:</b> shape first (a wrong shape fakes the other patterns), then spread, then time order, then single points.",
    take3Html: "<b>Healthy is boring:</b> a flat, even band around zero with no shape. Anything else is a clue, not a verdict. Check the notes from the session before changing the model.",
    take4Html: "<b>A clean residual plot still can't catch everything.</b> Noise in your x readings and unmeasured drift can bias the slope and leave the residuals looking fine. That's Module 5.",
    patternsTitle: "The four patterns",
    pat1Title: "A bend",
    pat1Body: "Wrong shape. Fit the model the physics gives you.",
    pat2Title: "A fan",
    pat2Body: "Uneven scatter. The line is fine; the error bars aren't. Module 3.",
    pat3Title: "A trend in run order",
    pat3Body: "Something changed during the session. Module 4.",
    pat4Title: "One point far away",
    pat4Body: "Check the notes, then check its influence. Don't just delete it.",
    footNote: "Simulated data. Trials 1 and 3: y = 1 + 2x + error. Trial 2: T = 22 + 58·e^(−t/4) + error, in °C and minutes.",
    footRead: "Further reading: Cook (1977), \"Detection of Influential Observation in Linear Regression\"; Cook and Weisberg (1982), Residuals and Influence in Regression; the NIST/SEMATECH e-Handbook of Statistical Methods."
  },
  es: {},
  // Reference chips (see learning-i18n.js): each phrase links once, where it first appears.
  chips: [
    { phrase: { en: "Cook's distance" }, href: "cook-1977.pdf" },
    { phrase: { en: "\"Detection of Influential Observation in Linear Regression\"" }, href: "cook-1977.pdf" },
    { phrase: { en: "Residuals and Influence in Regression" }, href: "cook-weisberg-1982.pdf" },
    { phrase: { en: "NIST/SEMATECH e-Handbook of Statistical Methods" }, href: "https://www.itl.nist.gov/div898/handbook/index.htm" }
  ]
};
